export interface USACityData {
  slug: string;
  name: string;
  state: string;
  region: 'west' | 'south' | 'southeast' | 'northeast' | 'midwest';
  tier: 1 | 2 | 3;
  population: string;
  constructionCost: { basic: number; standard: number; premium: number };
  laborCostPerDay: { mason: number; helper: number; painter: number };
  steelRatePerKg: number;
  cementBagRate: number;
  metaTitle: string;
  metaDescription: string;
  localBrands: string[];
  climateType: string;
  soilType: string;
  localTips: string[];
  neighborhoods: string[];
  nearbyCity?: string;
}

export const USA_CITIES: USACityData[] = [
  {
    slug: 'new-york-city',
    name: 'New York City',
    state: 'New York',
    region: 'northeast',
    tier: 1,
    population: '8.3M+',
    constructionCost: { basic: 250, standard: 400, premium: 700 },
    laborCostPerDay: { mason: 500, helper: 280, painter: 400 },
    steelRatePerKg: 1.45,
    cementBagRate: 19,
    metaTitle: 'Construction Cost & Renovation Answers for New York City | Biddaro',
    metaDescription:
      'Get accurate construction costs in New York City — $250 to $700 per sqft. Explore renovation rates for Manhattan, Brooklyn, Queens and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', 'Sherwin-Williams', 'James Hardie', 'GAF', 'CertainTeed'],
    climateType: 'Humid subtropical with cold winters',
    soilType: 'Rocky glacial till and sandy coastal soils',
    localTips: [
      'NYC Department of Buildings (DOB) permits are required for most renovation work — apply early as processing times can exceed 8 weeks.',
      'Buildings in flood zones (FEMA Zone AE) require elevated mechanical systems and flood-resistant materials per NYC Building Code.',
      'Energy code compliance under NYC Local Law 97 mandates strict carbon emission limits for buildings over 25,000 sqft.',
      'Older buildings may contain asbestos or lead paint — abatement must follow EPA and NYC DEP regulations before renovation.',
    ],
    neighborhoods: ['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island', 'Harlem', 'Williamsburg'],
    nearbyCity: 'philadelphia',
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    state: 'California',
    region: 'west',
    tier: 1,
    population: '3.9M+',
    constructionCost: { basic: 200, standard: 350, premium: 600 },
    laborCostPerDay: { mason: 450, helper: 260, painter: 380 },
    steelRatePerKg: 1.30,
    cementBagRate: 17,
    metaTitle: 'Construction Cost & Renovation Answers for Los Angeles | Biddaro',
    metaDescription:
      'Get accurate construction costs in Los Angeles — $200 to $600 per sqft. Explore renovation rates for Hollywood, Santa Monica, Downtown LA and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Behr', 'James Hardie', 'Eagle Roofing'],
    climateType: 'Mediterranean with dry summers and mild winters',
    soilType: 'Expansive clay and alluvial sandy soils',
    localTips: [
      'All construction must comply with California Building Code (CBC) seismic requirements — LA is in Seismic Design Category D/E.',
      'Title 24 energy efficiency standards require high-performance insulation and solar-ready roofing on new residential builds.',
      'Hillside construction in areas like Hollywood Hills requires geotechnical reports and slope stability analysis per LADBS guidelines.',
      'Wildfire-prone zones (Very High Fire Hazard Severity Zones) mandate fire-resistant roofing and exterior materials.',
    ],
    neighborhoods: ['Hollywood', 'Santa Monica', 'Downtown LA', 'Beverly Hills', 'Venice', 'Silver Lake', 'Pasadena'],
    nearbyCity: 'san-diego',
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    state: 'Illinois',
    region: 'midwest',
    tier: 1,
    population: '2.7M+',
    constructionCost: { basic: 180, standard: 300, premium: 500 },
    laborCostPerDay: { mason: 420, helper: 240, painter: 350 },
    steelRatePerKg: 1.20,
    cementBagRate: 16,
    metaTitle: 'Construction Cost & Renovation Answers for Chicago | Biddaro',
    metaDescription:
      'Get accurate construction costs in Chicago — $180 to $500 per sqft. Explore renovation rates for Lincoln Park, Wicker Park, Loop and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'CertainTeed', 'GAF'],
    climateType: 'Humid continental with harsh winters and warm summers',
    soilType: 'Clay-rich glacial soils with high water table',
    localTips: [
      'Chicago Building Code requires deep frost footings (minimum 42 inches) due to extreme freeze-thaw cycles.',
      'Basement waterproofing is critical — clay soils cause hydrostatic pressure; sump pumps and drain tiles are standard.',
      'Wind load requirements are elevated for high-rise and lakefront construction per Chicago Building Code amendments.',
      'Historic districts like Pullman and Old Town require Landmarks Commission approval before exterior modifications.',
    ],
    neighborhoods: ['Lincoln Park', 'Wicker Park', 'The Loop', 'Hyde Park', 'Lakeview', 'Logan Square', 'River North'],
    nearbyCity: 'indianapolis',
  },
  {
    slug: 'houston',
    name: 'Houston',
    state: 'Texas',
    region: 'south',
    tier: 1,
    population: '2.3M+',
    constructionCost: { basic: 140, standard: 220, premium: 400 },
    laborCostPerDay: { mason: 350, helper: 200, painter: 300 },
    steelRatePerKg: 1.00,
    cementBagRate: 14,
    metaTitle: 'Construction Cost & Renovation Answers for Houston | Biddaro',
    metaDescription:
      'Get accurate construction costs in Houston — $140 to $400 per sqft. Explore renovation rates for Montrose, The Heights, Katy and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Behr', 'GAF', 'James Hardie'],
    climateType: 'Humid subtropical with hot summers and mild winters',
    soilType: 'Expansive clay (Beaumont and Lissie formations)',
    localTips: [
      'Houston has no traditional zoning — verify deed restrictions and HOA covenants before starting construction.',
      'Flood risk is significant; FEMA floodplain maps should be checked, and elevated foundations are recommended in flood-prone areas.',
      'Expansive clay soils cause foundation movement — pier-and-beam or post-tension slab foundations are preferred.',
      'Hurricane-rated windows and roof tie-downs are essential per Texas Windstorm Insurance Association (TWIA) requirements.',
    ],
    neighborhoods: ['Montrose', 'The Heights', 'Katy', 'Sugar Land', 'Memorial', 'Midtown', 'River Oaks'],
    nearbyCity: 'san-antonio',
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    state: 'Arizona',
    region: 'west',
    tier: 1,
    population: '1.6M+',
    constructionCost: { basic: 150, standard: 230, premium: 380 },
    laborCostPerDay: { mason: 360, helper: 210, painter: 310 },
    steelRatePerKg: 1.05,
    cementBagRate: 15,
    metaTitle: 'Construction Cost & Renovation Answers for Phoenix | Biddaro',
    metaDescription:
      'Get accurate construction costs in Phoenix — $150 to $380 per sqft. Explore renovation rates for Scottsdale, Tempe, Chandler and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Dunn-Edwards', 'Behr', 'Eagle Roofing'],
    climateType: 'Hot desert with extreme summer heat and mild winters',
    soilType: 'Caliche (calcium carbonate hardpan) and sandy desert soils',
    localTips: [
      'Extreme heat requires reflective roofing materials and enhanced insulation — IECC climate zone 2B energy code applies.',
      'Caliche layers can complicate excavation and require specialized equipment; soil testing is essential before foundation work.',
      'Pool construction is common but must comply with Maricopa County barrier and safety requirements.',
      'Low-water landscaping (xeriscaping) is encouraged and may be required by municipal water conservation ordinances.',
    ],
    neighborhoods: ['Scottsdale', 'Tempe', 'Chandler', 'Mesa', 'Arcadia', 'Ahwatukee', 'Gilbert'],
    nearbyCity: 'las-vegas',
  },
  {
    slug: 'philadelphia',
    name: 'Philadelphia',
    state: 'Pennsylvania',
    region: 'northeast',
    tier: 1,
    population: '1.6M+',
    constructionCost: { basic: 170, standard: 280, premium: 480 },
    laborCostPerDay: { mason: 430, helper: 250, painter: 360 },
    steelRatePerKg: 1.25,
    cementBagRate: 17,
    metaTitle: 'Construction Cost & Renovation Answers for Philadelphia | Biddaro',
    metaDescription:
      'Get accurate construction costs in Philadelphia — $170 to $480 per sqft. Explore renovation rates for Center City, Fishtown, Rittenhouse and more with Biddaro.',
    localBrands: ['Home Depot', 'Sherwin-Williams', "Lowe's", 'GAF', 'CertainTeed'],
    climateType: 'Humid subtropical with warm summers and cold winters',
    soilType: 'Piedmont clay and coastal plain sandy soils',
    localTips: [
      'Philadelphia L&I (Licenses & Inspections) permits are required for most construction — online applications expedite processing.',
      'Historic rowhouse renovations in areas like Old City and Society Hill must comply with Philadelphia Historical Commission guidelines.',
      'Stormwater management is strictly enforced — impervious surface additions require on-site retention per PWD regulations.',
      'Lead paint abatement is mandatory in pre-1978 buildings and must follow EPA RRP Rule requirements.',
    ],
    neighborhoods: ['Center City', 'Fishtown', 'Rittenhouse Square', 'Old City', 'Northern Liberties', 'Manayunk', 'University City'],
    nearbyCity: 'new-york-city',
  },
  {
    slug: 'san-antonio',
    name: 'San Antonio',
    state: 'Texas',
    region: 'south',
    tier: 1,
    population: '1.5M+',
    constructionCost: { basic: 130, standard: 200, premium: 360 },
    laborCostPerDay: { mason: 320, helper: 190, painter: 280 },
    steelRatePerKg: 0.95,
    cementBagRate: 13,
    metaTitle: 'Construction Cost & Renovation Answers for San Antonio | Biddaro',
    metaDescription:
      'Get accurate construction costs in San Antonio — $130 to $360 per sqft. Explore renovation rates for Alamo Heights, Stone Oak, Southtown and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Behr', 'James Hardie', 'GAF'],
    climateType: 'Humid subtropical with hot summers and mild winters',
    soilType: 'Limestone and expansive black clay (Houston Black series)',
    localTips: [
      'Expansive clay soils are prevalent — post-tension slab foundations with proper drainage are recommended.',
      'Construction over the Edwards Aquifer Recharge Zone requires TCEQ environmental compliance and impervious cover limits.',
      'San Antonio Development Services Department handles permits — plan reviews typically take 2-4 weeks.',
      'Historic districts near the River Walk and King William require HDRC (Historic Design Review Commission) approval.',
    ],
    neighborhoods: ['Alamo Heights', 'Stone Oak', 'Southtown', 'King William', 'The Pearl', 'Helotes'],
    nearbyCity: 'austin',
  },
  {
    slug: 'san-diego',
    name: 'San Diego',
    state: 'California',
    region: 'west',
    tier: 1,
    population: '1.4M+',
    constructionCost: { basic: 190, standard: 320, premium: 550 },
    laborCostPerDay: { mason: 440, helper: 255, painter: 370 },
    steelRatePerKg: 1.30,
    cementBagRate: 17,
    metaTitle: 'Construction Cost & Renovation Answers for San Diego | Biddaro',
    metaDescription:
      'Get accurate construction costs in San Diego — $190 to $550 per sqft. Explore renovation rates for La Jolla, North Park, Gaslamp and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', 'Dunn-Edwards', 'James Hardie', 'Behr', 'CertainTeed'],
    climateType: 'Semi-arid Mediterranean with mild year-round temperatures',
    soilType: 'Sandy coastal soils and inland clay formations',
    localTips: [
      'California Building Code seismic requirements apply — San Diego is in Seismic Design Category D.',
      'Coastal construction within the Coastal Zone requires California Coastal Commission permits in addition to city permits.',
      'Title 24 energy standards mandate solar-ready construction and high-efficiency HVAC for new residential builds.',
      'Hillside and canyon-adjacent properties may require brush management plans for wildfire mitigation.',
    ],
    neighborhoods: ['La Jolla', 'North Park', 'Gaslamp Quarter', 'Pacific Beach', 'Hillcrest', 'Coronado', 'Del Mar'],
    nearbyCity: 'los-angeles',
  },
  {
    slug: 'dallas',
    name: 'Dallas',
    state: 'Texas',
    region: 'south',
    tier: 1,
    population: '1.3M+',
    constructionCost: { basic: 150, standard: 240, premium: 420 },
    laborCostPerDay: { mason: 370, helper: 215, painter: 310 },
    steelRatePerKg: 1.05,
    cementBagRate: 14,
    metaTitle: 'Construction Cost & Renovation Answers for Dallas | Biddaro',
    metaDescription:
      'Get accurate construction costs in Dallas — $150 to $420 per sqft. Explore renovation rates for Uptown, Highland Park, Deep Ellum and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'GAF', 'James Hardie'],
    climateType: 'Humid subtropical with hot summers and mild winters',
    soilType: 'Expansive Austin Chalk and Eagle Ford clay',
    localTips: [
      'Expansive clay soils cause significant foundation movement — regular watering of foundation perimeters is advised.',
      'Dallas permits are processed through the Dallas Building Inspection Division — express reviews available for simple projects.',
      'Tornado-prone area; safe rooms and reinforced interior closets are recommended per ICC 500 standard.',
      'Energy code compliance follows IECC 2021 as adopted by Texas — verify insulation and HVAC efficiency requirements.',
    ],
    neighborhoods: ['Uptown', 'Highland Park', 'Deep Ellum', 'Bishop Arts', 'Lakewood', 'Oak Lawn', 'Preston Hollow'],
    nearbyCity: 'houston',
  },
  {
    slug: 'austin',
    name: 'Austin',
    state: 'Texas',
    region: 'south',
    tier: 1,
    population: '1M+',
    constructionCost: { basic: 160, standard: 260, premium: 440 },
    laborCostPerDay: { mason: 380, helper: 220, painter: 320 },
    steelRatePerKg: 1.10,
    cementBagRate: 15,
    metaTitle: 'Construction Cost & Renovation Answers for Austin | Biddaro',
    metaDescription:
      'Get accurate construction costs in Austin — $160 to $440 per sqft. Explore renovation rates for South Congress, East Austin, Zilker and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Behr', 'Sherwin-Williams', 'GAF'],
    climateType: 'Humid subtropical with hot summers and mild winters',
    soilType: 'Limestone bedrock with expansive clay pockets',
    localTips: [
      'Austin is in the Edwards Aquifer Contributing Zone — impervious cover limits and water quality controls apply per City Code.',
      'Tree preservation ordinance protects heritage trees over 19 inches in diameter — removal requires a variance.',
      'Austin Energy Green Building program rates projects; high ratings may qualify for expedited permitting.',
      'Flash flooding is common — check FEMA floodplain status and avoid building in 100-year floodplain without proper elevation.',
    ],
    neighborhoods: ['South Congress (SoCo)', 'East Austin', 'Zilker', 'Downtown', 'Mueller', 'Hyde Park', 'Barton Hills'],
    nearbyCity: 'san-antonio',
  },
  {
    slug: 'san-francisco',
    name: 'San Francisco',
    state: 'California',
    region: 'west',
    tier: 1,
    population: '870K+',
    constructionCost: { basic: 300, standard: 500, premium: 900 },
    laborCostPerDay: { mason: 500, helper: 280, painter: 400 },
    steelRatePerKg: 1.50,
    cementBagRate: 20,
    metaTitle: 'Construction Cost & Renovation Answers for San Francisco | Biddaro',
    metaDescription:
      'Get accurate construction costs in San Francisco — $300 to $900 per sqft. Explore renovation rates for Mission, SOMA, Pacific Heights and more with Biddaro.',
    localBrands: ['Home Depot', 'Sherwin-Williams', 'James Hardie', 'CertainTeed', 'Dunn-Edwards'],
    climateType: 'Cool Mediterranean with fog and mild temperatures year-round',
    soilType: 'Sandy fill, bay mud, and serpentinite bedrock',
    localTips: [
      'Seismic retrofit requirements are strict — soft-story buildings must comply with SF Mandatory Seismic Retrofit Program.',
      'SF Planning Department review can take 6-12 months for discretionary permits in residential neighborhoods.',
      'Title 24 and SF Green Building Code require advanced energy efficiency, solar panels, and EV-ready parking.',
      'Soil liquefaction risk in SOMA and Marina districts requires deep foundation systems and geotechnical engineering.',
    ],
    neighborhoods: ['Mission District', 'SOMA', 'Pacific Heights', 'Marina', 'Castro', 'Noe Valley', 'Haight-Ashbury'],
    nearbyCity: 'san-diego',
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    state: 'Washington',
    region: 'west',
    tier: 1,
    population: '740K+',
    constructionCost: { basic: 220, standard: 370, premium: 650 },
    laborCostPerDay: { mason: 460, helper: 260, painter: 380 },
    steelRatePerKg: 1.35,
    cementBagRate: 18,
    metaTitle: 'Construction Cost & Renovation Answers for Seattle | Biddaro',
    metaDescription:
      'Get accurate construction costs in Seattle — $220 to $650 per sqft. Explore renovation rates for Capitol Hill, Ballard, Fremont and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'James Hardie', 'GAF'],
    climateType: 'Oceanic with mild, wet winters and dry summers',
    soilType: 'Glacial till, clay, and sandy soils with high water table',
    localTips: [
      'Seattle is in Seismic Design Category D — unreinforced masonry buildings require seismic retrofit per city ordinance.',
      'Moisture management is critical — continuous rain screens, vapor barriers, and proper drainage are essential.',
      'Seattle Department of Construction & Inspections (SDCI) manages permits — pre-application conferences recommended for larger projects.',
      'Energy code follows Washington State Energy Code (WSEC), which exceeds IECC standards for insulation and air sealing.',
    ],
    neighborhoods: ['Capitol Hill', 'Ballard', 'Fremont', 'Queen Anne', 'Georgetown', 'West Seattle', 'Wallingford'],
    nearbyCity: 'portland',
  },
  {
    slug: 'denver',
    name: 'Denver',
    state: 'Colorado',
    region: 'west',
    tier: 1,
    population: '710K+',
    constructionCost: { basic: 180, standard: 290, premium: 480 },
    laborCostPerDay: { mason: 400, helper: 230, painter: 340 },
    steelRatePerKg: 1.15,
    cementBagRate: 16,
    metaTitle: 'Construction Cost & Renovation Answers for Denver | Biddaro',
    metaDescription:
      'Get accurate construction costs in Denver — $180 to $480 per sqft. Explore renovation rates for LoDo, Cherry Creek, Capitol Hill and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'Behr', 'CertainTeed'],
    climateType: 'Semi-arid continental with cold winters and sunny summers',
    soilType: 'Expansive bentonite clay (Denver Formation)',
    localTips: [
      'Denver expansive soils (bentonite clay) require engineered foundations — pier systems are common in many neighborhoods.',
      'Hailstorms are frequent — impact-resistant roofing (Class 4) qualifies for insurance discounts and is highly recommended.',
      'Denver Green Code applies to commercial projects; residential builds must meet 2021 IECC energy standards.',
      'Altitude (5,280 ft) affects HVAC sizing and concrete curing — adjust mix designs and equipment ratings accordingly.',
    ],
    neighborhoods: ['LoDo', 'Cherry Creek', 'Capitol Hill', 'Highlands', 'Washington Park', 'RiNo'],
    nearbyCity: 'phoenix',
  },
  {
    slug: 'boston',
    name: 'Boston',
    state: 'Massachusetts',
    region: 'northeast',
    tier: 1,
    population: '700K+',
    constructionCost: { basic: 230, standard: 380, premium: 650 },
    laborCostPerDay: { mason: 480, helper: 270, painter: 390 },
    steelRatePerKg: 1.40,
    cementBagRate: 19,
    metaTitle: 'Construction Cost & Renovation Answers for Boston | Biddaro',
    metaDescription:
      'Get accurate construction costs in Boston — $230 to $650 per sqft. Explore renovation rates for Back Bay, South End, Cambridge and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', 'Sherwin-Williams', "Lowe's", 'GAF', 'CertainTeed'],
    climateType: 'Humid continental with cold, snowy winters and warm summers',
    soilType: 'Fill over marine clay (Boston Blue Clay) and glacial till',
    localTips: [
      'Boston Blue Clay requires deep foundations for heavy structures — geotechnical reports are essential in Back Bay and waterfront areas.',
      'Boston Inspectional Services Department (ISD) issues permits — landmark buildings require Boston Landmarks Commission approval.',
      'Massachusetts Stretch Energy Code (optional municipal adoption) exceeds base energy code and applies in many surrounding communities.',
      'Nor\'easters and heavy snowfall require robust roof load design — minimum 40 psf snow load per Massachusetts Building Code.',
    ],
    neighborhoods: ['Back Bay', 'South End', 'Beacon Hill', 'Cambridge', 'Somerville', 'Jamaica Plain', 'Charlestown'],
    nearbyCity: 'new-york-city',
  },
  {
    slug: 'nashville',
    name: 'Nashville',
    state: 'Tennessee',
    region: 'south',
    tier: 1,
    population: '690K+',
    constructionCost: { basic: 150, standard: 240, premium: 400 },
    laborCostPerDay: { mason: 350, helper: 200, painter: 300 },
    steelRatePerKg: 1.00,
    cementBagRate: 14,
    metaTitle: 'Construction Cost & Renovation Answers for Nashville | Biddaro',
    metaDescription:
      'Get accurate construction costs in Nashville — $150 to $400 per sqft. Explore renovation rates for East Nashville, The Gulch, Germantown and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'GAF', 'Behr'],
    climateType: 'Humid subtropical with hot summers and mild winters',
    soilType: 'Limestone bedrock with residual clay soils',
    localTips: [
      'Nashville Codes Department issues building permits — online applications available for standard residential work.',
      'Tornado risk is moderate — safe rooms and reinforced storm shelters are recommended per ICC 500.',
      'Stormwater management regulations require detention for new impervious surfaces per Metro Water Services standards.',
      'Historic overlay districts (such as Lockeland Springs) require MHZC approval for exterior changes.',
    ],
    neighborhoods: ['East Nashville', 'The Gulch', 'Germantown', '12 South', 'Sylvan Park', 'Green Hills'],
    nearbyCity: 'atlanta',
  },
  {
    slug: 'atlanta',
    name: 'Atlanta',
    state: 'Georgia',
    region: 'southeast',
    tier: 1,
    population: '500K+',
    constructionCost: { basic: 150, standard: 240, premium: 400 },
    laborCostPerDay: { mason: 360, helper: 210, painter: 310 },
    steelRatePerKg: 1.05,
    cementBagRate: 14,
    metaTitle: 'Construction Cost & Renovation Answers for Atlanta | Biddaro',
    metaDescription:
      'Get accurate construction costs in Atlanta — $150 to $400 per sqft. Explore renovation rates for Buckhead, Midtown, Decatur and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'Behr', 'GAF'],
    climateType: 'Humid subtropical with hot summers and mild winters',
    soilType: 'Red clay (Cecil and Pacolet series) over Piedmont bedrock',
    localTips: [
      'Georgia red clay soil is expansive and poorly draining — proper grading and foundation drainage systems are critical.',
      'Atlanta requires tree canopy replacement per Tree Protection Ordinance — removal permits needed for trees over 6 inches DBH.',
      'City of Atlanta Office of Buildings issues permits — plan review takes 2-4 weeks for residential projects.',
      'Termite pressure is high in the Southeast — soil treatment and termite barriers are required per Georgia Building Code.',
    ],
    neighborhoods: ['Buckhead', 'Midtown', 'Decatur', 'Virginia-Highland', 'Inman Park', 'Grant Park', 'Old Fourth Ward'],
    nearbyCity: 'charlotte',
  },
  {
    slug: 'miami',
    name: 'Miami',
    state: 'Florida',
    region: 'southeast',
    tier: 1,
    population: '450K+',
    constructionCost: { basic: 180, standard: 300, premium: 520 },
    laborCostPerDay: { mason: 400, helper: 235, painter: 340 },
    steelRatePerKg: 1.20,
    cementBagRate: 16,
    metaTitle: 'Construction Cost & Renovation Answers for Miami | Biddaro',
    metaDescription:
      'Get accurate construction costs in Miami — $180 to $520 per sqft. Explore renovation rates for Brickell, Coral Gables, Wynwood and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'GAF', 'James Hardie'],
    climateType: 'Tropical monsoon with hot, humid summers and warm winters',
    soilType: 'Porous oolitic limestone (Miami Limestone) and sandy marl',
    localTips: [
      'Miami-Dade County requires hurricane-rated windows and doors (Large Missile Impact rated) — Florida Building Code High-Velocity Hurricane Zone applies.',
      'Flood zone compliance is critical — most of Miami requires elevated construction per FEMA and local floodplain ordinances.',
      'Salt air corrosion requires stainless steel fasteners, galvanized metals, and marine-grade exterior finishes.',
      'Miami-Dade Building Department Notice of Commencement must be filed before work begins on permitted projects.',
    ],
    neighborhoods: ['Brickell', 'Coral Gables', 'Wynwood', 'Coconut Grove', 'Little Havana', 'Miami Beach', 'Design District'],
    nearbyCity: 'orlando',
  },
  {
    slug: 'charlotte',
    name: 'Charlotte',
    state: 'North Carolina',
    region: 'southeast',
    tier: 1,
    population: '880K+',
    constructionCost: { basic: 140, standard: 220, premium: 380 },
    laborCostPerDay: { mason: 340, helper: 195, painter: 290 },
    steelRatePerKg: 1.00,
    cementBagRate: 14,
    metaTitle: 'Construction Cost & Renovation Answers for Charlotte | Biddaro',
    metaDescription:
      'Get accurate construction costs in Charlotte — $140 to $380 per sqft. Explore renovation rates for South End, NoDa, Dilworth and more neighborhoods with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'CertainTeed', 'GAF'],
    climateType: 'Humid subtropical with hot summers and mild winters',
    soilType: 'Red Piedmont clay over weathered granite and gneiss',
    localTips: [
      'Charlotte-Mecklenburg permits are managed through Code Enforcement — residential reviews typically take 10-15 business days.',
      'Red clay soils require proper compaction and drainage — erosion and sediment control plans are required for land disturbance.',
      'NC Energy Conservation Code follows IECC standards — verify insulation R-values and window U-factors for climate zone 3A.',
      'Tree preservation ordinances protect large trees on development sites — mitigation fees apply for removals.',
    ],
    neighborhoods: ['South End', 'NoDa', 'Dilworth', 'Plaza Midwood', 'Myers Park', 'Ballantyne', 'University City'],
    nearbyCity: 'atlanta',
  },
  {
    slug: 'portland',
    name: 'Portland',
    state: 'Oregon',
    region: 'west',
    tier: 2,
    population: '650K+',
    constructionCost: { basic: 190, standard: 310, premium: 520 },
    laborCostPerDay: { mason: 430, helper: 245, painter: 360 },
    steelRatePerKg: 1.25,
    cementBagRate: 17,
    metaTitle: 'Construction Cost & Renovation Answers for Portland | Biddaro',
    metaDescription:
      'Get accurate construction costs in Portland — $190 to $520 per sqft. Explore renovation rates for Pearl District, Alberta, Hawthorne and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'James Hardie', 'CertainTeed'],
    climateType: 'Oceanic with wet winters and dry, warm summers',
    soilType: 'Alluvial silt and clay (Willamette Valley) with volcanic soils on hills',
    localTips: [
      'Portland Bureau of Development Services (BDS) manages permits — online tracking and digital submissions available.',
      'Seismic retrofit incentives exist — Portland is in Seismic Design Category D due to Cascadia Subduction Zone risk.',
      'Oregon Reach Code and Portland-specific energy mandates require high-performance building envelopes and heat pumps.',
      'Stormwater management is strictly enforced — rain gardens and eco-roofs earn fee reductions from BES.',
    ],
    neighborhoods: ['Pearl District', 'Alberta Arts', 'Hawthorne', 'Division', 'Sellwood', 'St. Johns', 'Nob Hill'],
    nearbyCity: 'seattle',
  },
  {
    slug: 'las-vegas',
    name: 'Las Vegas',
    state: 'Nevada',
    region: 'west',
    tier: 1,
    population: '650K+',
    constructionCost: { basic: 150, standard: 240, premium: 400 },
    laborCostPerDay: { mason: 370, helper: 215, painter: 310 },
    steelRatePerKg: 1.10,
    cementBagRate: 15,
    metaTitle: 'Construction Cost & Renovation Answers for Las Vegas | Biddaro',
    metaDescription:
      'Get accurate construction costs in Las Vegas — $150 to $400 per sqft. Explore renovation rates for Summerlin, Henderson, Downtown and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Dunn-Edwards', 'Behr', 'GAF'],
    climateType: 'Hot desert with extreme summer heat and mild winters',
    soilType: 'Caliche hardpan, sandy desert soils, and alluvial gravel',
    localTips: [
      'Caliche soil layers are extremely hard — specialized excavation equipment needed; soil reports required before foundation work.',
      'Extreme heat (115F+) requires cool roofing materials, enhanced insulation per IECC climate zone 3B, and shade structures.',
      'Clark County Building Department handles permits for unincorporated areas — city permits for Las Vegas proper.',
      'Flash flood risk in desert washes — verify FEMA flood maps and avoid building in designated flood channels.',
    ],
    neighborhoods: ['Summerlin', 'Henderson', 'Downtown', 'Spring Valley', 'Green Valley', 'North Las Vegas'],
    nearbyCity: 'phoenix',
  },
  {
    slug: 'detroit',
    name: 'Detroit',
    state: 'Michigan',
    region: 'midwest',
    tier: 1,
    population: '640K+',
    constructionCost: { basic: 130, standard: 200, premium: 350 },
    laborCostPerDay: { mason: 380, helper: 210, painter: 310 },
    steelRatePerKg: 1.05,
    cementBagRate: 15,
    metaTitle: 'Construction Cost & Renovation Answers for Detroit | Biddaro',
    metaDescription:
      'Get accurate construction costs in Detroit — $130 to $350 per sqft. Explore renovation rates for Midtown, Corktown, Grosse Pointe and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'GAF', 'CertainTeed'],
    climateType: 'Humid continental with cold, snowy winters and warm summers',
    soilType: 'Glacial clay and sandy lacustrine soils',
    localTips: [
      'Detroit Building Authority manages permits — renovation incentives and tax abatements available through Neighborhood Enterprise Zone (NEZ) program.',
      'Deep frost footings (42+ inches) required due to freeze-thaw cycles in Michigan climate zone 5A.',
      'Historic renovation tax credits (state and federal) available for qualifying properties in historic districts.',
      'Basement waterproofing is essential — high water table and clay soils create significant moisture infiltration risk.',
    ],
    neighborhoods: ['Midtown', 'Corktown', 'Grosse Pointe', 'Indian Village', 'Palmer Park', 'West Village'],
    nearbyCity: 'columbus',
  },
  {
    slug: 'minneapolis',
    name: 'Minneapolis',
    state: 'Minnesota',
    region: 'midwest',
    tier: 2,
    population: '430K+',
    constructionCost: { basic: 170, standard: 270, premium: 450 },
    laborCostPerDay: { mason: 410, helper: 235, painter: 340 },
    steelRatePerKg: 1.15,
    cementBagRate: 16,
    metaTitle: 'Construction Cost & Renovation Answers for Minneapolis | Biddaro',
    metaDescription:
      'Get accurate construction costs in Minneapolis — $170 to $450 per sqft. Explore renovation rates for Uptown, North Loop, Linden Hills and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'Behr', 'Andersen Windows'],
    climateType: 'Humid continental with very cold winters and warm summers',
    soilType: 'Glacial till with clay and sandy layers',
    localTips: [
      'Extreme cold (climate zone 6A) demands high-performance insulation — R-49 attic and R-20 wall insulation minimum per Minnesota Energy Code.',
      'Frost footings must extend 60 inches below grade — the deepest frost line requirement in the contiguous US.',
      'Minneapolis Community Planning & Economic Development (CPED) processes permits — online portal available for standard applications.',
      'Ice damming prevention requires proper attic ventilation, air sealing, and ice-and-water shield underlayment on roofs.',
    ],
    neighborhoods: ['Uptown', 'North Loop', 'Linden Hills', 'Northeast', 'Lowry Hill', 'Nokomis'],
    nearbyCity: 'chicago',
  },
  {
    slug: 'orlando',
    name: 'Orlando',
    state: 'Florida',
    region: 'southeast',
    tier: 2,
    population: '310K+',
    constructionCost: { basic: 160, standard: 250, premium: 420 },
    laborCostPerDay: { mason: 350, helper: 200, painter: 300 },
    steelRatePerKg: 1.05,
    cementBagRate: 15,
    metaTitle: 'Construction Cost & Renovation Answers for Orlando | Biddaro',
    metaDescription:
      'Get accurate construction costs in Orlando — $160 to $420 per sqft. Explore renovation rates for Winter Park, Dr. Phillips, College Park and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'GAF', 'Behr'],
    climateType: 'Humid subtropical with hot, rainy summers and mild winters',
    soilType: 'Sandy soils with high water table and occasional sinkhole-prone limestone',
    localTips: [
      'Florida Building Code hurricane provisions apply — wind-rated windows and roof-to-wall tie-downs are mandatory.',
      'Sinkhole risk is real in Central Florida — geo-investigation and sinkhole insurance should be considered before construction.',
      'High water table requires careful foundation design — slab-on-grade is standard; basements are extremely rare.',
      'Orange County and City of Orlando have separate permit processes — verify jurisdiction before applying.',
    ],
    neighborhoods: ['Winter Park', 'Dr. Phillips', 'College Park', 'Thornton Park', 'Baldwin Park', 'Lake Nona'],
    nearbyCity: 'miami',
  },
  {
    slug: 'columbus',
    name: 'Columbus',
    state: 'Ohio',
    region: 'midwest',
    tier: 2,
    population: '900K+',
    constructionCost: { basic: 140, standard: 220, premium: 370 },
    laborCostPerDay: { mason: 360, helper: 205, painter: 300 },
    steelRatePerKg: 1.00,
    cementBagRate: 14,
    metaTitle: 'Construction Cost & Renovation Answers for Columbus | Biddaro',
    metaDescription:
      'Get accurate construction costs in Columbus — $140 to $370 per sqft. Explore renovation rates for Short North, German Village, Dublin and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'CertainTeed', 'GAF'],
    climateType: 'Humid continental with cold winters and warm, humid summers',
    soilType: 'Glacial till with clay and shale bedrock',
    localTips: [
      'Columbus Building & Zoning Services handles permits — plan review for residential projects takes approximately 10 business days.',
      'Frost depth is 32 inches — all footings must extend below this depth per Ohio Building Code.',
      'German Village and other historic districts require Columbus Historic Resources Commission approval for exterior changes.',
      'Stormwater management per Columbus City Code requires on-site detention for projects adding significant impervious surface.',
    ],
    neighborhoods: ['Short North', 'German Village', 'Dublin', 'Clintonville', 'Grandview Heights', 'Worthington', 'Upper Arlington'],
    nearbyCity: 'indianapolis',
  },
  {
    slug: 'indianapolis',
    name: 'Indianapolis',
    state: 'Indiana',
    region: 'midwest',
    tier: 2,
    population: '890K+',
    constructionCost: { basic: 130, standard: 210, premium: 360 },
    laborCostPerDay: { mason: 340, helper: 195, painter: 290 },
    steelRatePerKg: 0.95,
    cementBagRate: 13,
    metaTitle: 'Construction Cost & Renovation Answers for Indianapolis | Biddaro',
    metaDescription:
      'Get accurate construction costs in Indianapolis — $130 to $360 per sqft. Explore renovation rates for Broad Ripple, Fountain Square, Carmel and more with Biddaro.',
    localBrands: ['Home Depot', "Lowe's", 'Sherwin-Williams', 'Behr', 'GAF'],
    climateType: 'Humid continental with cold winters and warm, humid summers',
    soilType: 'Glacial till with clay and sandy loam',
    localTips: [
      'Indianapolis Department of Business & Neighborhood Services (BNS) issues building permits — online applications accepted.',
      'Frost footings must extend 36 inches below grade per Indiana Building Code for climate zone 5A.',
      'Tornado risk is moderate — FEMA recommends safe rooms per ICC 500; reinforced interior rooms are advisable.',
      'Historic neighborhoods like Lockerbie Square and Old Northside require Indianapolis Historic Preservation Commission approval.',
    ],
    neighborhoods: ['Broad Ripple', 'Fountain Square', 'Carmel', 'Mass Ave', 'Irvington', 'Meridian-Kessler', 'Zionsville'],
    nearbyCity: 'columbus',
  },
];

export function getUSACityBySlug(slug: string): USACityData | undefined {
  return USA_CITIES.find((c) => c.slug === slug);
}
