export interface SGCityData {
  slug: string;
  name: string;
  region: string;
  planningArea: string;
  tier: 1 | 2 | 3;
  population: string;
  constructionCost: { basic: number; standard: number; premium: number };
  laborCostPerDay: { mason: number; helper: number; painter: number };
  steelRatePerKg: number;
  cementBagRate: number;
  metaTitle: string;
  metaDescription: string;
  localBrands: string[];
  climateType: string;
  soilType: string;
  localTips: string[];
  neighborhoods: string[];
  nearbyDistrict?: string;
}

export const SG_CITIES: SGCityData[] = [
  {
    slug: "downtown-core",
    name: "Downtown Core",
    region: "Central",
    planningArea: "Downtown Core",
    tier: 1,
    population: "50,000+",
    constructionCost: { basic: 350, standard: 550, premium: 900 },
    laborCostPerDay: { mason: 200, helper: 100, painter: 180 },
    steelRatePerKg: 1.8,
    cementBagRate: 12,
    metaTitle: "Construction Cost & Renovation Answers for Downtown Core | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Downtown Core, Singapore. Basic from SGD 350/sqft, standard SGD 550/sqft, premium SGD 900/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Kansai Paint", "Kim Hin", "Hoe Kee Hardware", "BMS Building Materials"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Reclaimed land and marine clay; deep foundation piling often required",
    localTips: [
      "BCA regulations require a licensed builder for any structural work in the CBD area. Ensure your contractor holds a valid BCA license.",
      "Renovation work in Downtown Core is subject to strict noise restrictions — no work allowed between 5:30 PM and 9:00 AM on weekdays and all day on Sundays and public holidays.",
      "URA guidelines in the Central Area impose height limits and plot ratio controls; always verify your renovation plans comply with the Master Plan.",
      "Tropical humidity demands waterproofing treatment for all exposed surfaces — budget an additional SGD 5-10/sqft for proper moisture barrier application.",
    ],
    neighborhoods: ["Raffles Place", "Shenton Way", "Marina Centre", "Tanjong Pagar", "Cecil Street", "Boat Quay"],
    nearbyDistrict: "marina-bay",
  },
  {
    slug: "orchard",
    name: "Orchard",
    region: "Central",
    planningArea: "Orchard",
    tier: 1,
    population: "30,000+",
    constructionCost: { basic: 320, standard: 500, premium: 850 },
    laborCostPerDay: { mason: 190, helper: 95, painter: 170 },
    steelRatePerKg: 1.7,
    cementBagRate: 11,
    metaTitle: "Construction Cost & Renovation Answers for Orchard | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Orchard, Singapore. Basic from SGD 320/sqft, standard SGD 500/sqft, premium SGD 850/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Dulux", "Hoe Kee Hardware", "Kim Hin", "Hafary"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Alluvial deposits over Old Alluvium; generally stable ground conditions",
    localTips: [
      "BCA mandates that all renovation contractors working on residential properties must be HDB-registered if working on HDB flats, or hold relevant BCA licenses for private condominiums.",
      "Noise restrictions in Orchard residential areas are enforced strictly — renovation work is prohibited between 5:30 PM and 9:00 AM.",
      "URA conservation guidelines apply to parts of Orchard near Emerald Hill — check if your property falls within a conservation zone before planning major structural changes.",
      "High humidity in Singapore means you should opt for moisture-resistant materials and anti-mould paint formulations for long-lasting finishes.",
    ],
    neighborhoods: ["Tanglin", "Paterson", "Cairnhill", "Emerald Hill", "Claymore", "Bideford"],
    nearbyDistrict: "downtown-core",
  },
  {
    slug: "tampines",
    name: "Tampines",
    region: "East",
    planningArea: "Tampines",
    tier: 1,
    population: "260,000+",
    constructionCost: { basic: 250, standard: 380, premium: 600 },
    laborCostPerDay: { mason: 150, helper: 85, painter: 130 },
    steelRatePerKg: 1.4,
    cementBagRate: 9,
    metaTitle: "Construction Cost & Renovation Answers for Tampines | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Tampines, Singapore. Basic from SGD 250/sqft, standard SGD 380/sqft, premium SGD 600/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Sheng Siong Building Materials", "Hoe Kee Hardware", "HomeFix", "Kim Hin"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Old Alluvium formation; generally good bearing capacity for standard foundations",
    localTips: [
      "HDB renovation permits are mandatory for all flat renovations in Tampines — apply through the HDB e-Service portal at least 3 days before commencing work.",
      "Renovation noise restrictions apply from 5:30 PM to 9:00 AM daily; weekend work requires prior approval from the Town Council.",
      "BCA-approved contractors are recommended for wet-area waterproofing — Tampines flats near the coast may experience higher moisture levels.",
      "Consider using tropical-grade timber and corrosion-resistant fixtures given the high humidity and occasional heavy downpours in the East region.",
    ],
    neighborhoods: ["Tampines Central", "Tampines North", "Tampines East", "Tampines West", "Simei", "Pasir Ris border"],
    nearbyDistrict: "bedok",
  },
  {
    slug: "bedok",
    name: "Bedok",
    region: "East",
    planningArea: "Bedok",
    tier: 1,
    population: "290,000+",
    constructionCost: { basic: 240, standard: 370, premium: 580 },
    laborCostPerDay: { mason: 145, helper: 82, painter: 125 },
    steelRatePerKg: 1.4,
    cementBagRate: 9,
    metaTitle: "Construction Cost & Renovation Answers for Bedok | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Bedok, Singapore. Basic from SGD 240/sqft, standard SGD 370/sqft, premium SGD 580/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Kansai Paint", "Sheng Siong Building Materials", "HomeFix", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Old Alluvium and marine clay; piling may be needed for deeper foundations near the coast",
    localTips: [
      "All HDB flat renovations in Bedok require an approved renovation permit — contractors must be listed on HDB's Directory of Renovation Contractors.",
      "Strict noise restrictions apply: no renovation work between 5:30 PM and 9:00 AM. Violations can result in fines from the Town Council.",
      "Bedok's proximity to the coast means salt air exposure — use marine-grade stainless steel fixtures and anti-corrosion treatments for external works.",
      "BCA guidelines require proper disposal of renovation debris; engage a licensed waste collector to avoid penalties.",
    ],
    neighborhoods: ["Bedok North", "Bedok South", "Bedok Reservoir", "Kaki Bukit", "Chai Chee", "Frankel Estate", "Siglap"],
    nearbyDistrict: "tampines",
  },
  {
    slug: "jurong-east",
    name: "Jurong East",
    region: "West",
    planningArea: "Jurong East",
    tier: 1,
    population: "85,000+",
    constructionCost: { basic: 230, standard: 360, premium: 560 },
    laborCostPerDay: { mason: 140, helper: 80, painter: 120 },
    steelRatePerKg: 1.3,
    cementBagRate: 9,
    metaTitle: "Construction Cost & Renovation Answers for Jurong East | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Jurong East, Singapore. Basic from SGD 230/sqft, standard SGD 360/sqft, premium SGD 560/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Kansai Paint", "Sheng Siong Building Materials", "Kim Hin", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Jurong Formation sedimentary rock; generally stable with good load-bearing capacity",
    localTips: [
      "Jurong East is a key node in the Jurong Lake District masterplan — check URA's plans for upcoming infrastructure changes that could affect your property value and renovation scope.",
      "HDB renovation permits must be obtained before starting any work; apply online through HDB's e-Service portal.",
      "Noise restrictions from 5:30 PM to 9:00 AM are enforced — plan heavy demolition and drilling work during approved daytime hours.",
      "Tropical downpours are common; ensure all renovation work includes adequate waterproofing and drainage, especially for ground-floor units.",
    ],
    neighborhoods: ["Jurong Gateway", "Lakeside", "Toh Guan", "Teban Gardens", "Pandan Gardens"],
    nearbyDistrict: "jurong-west",
  },
  {
    slug: "jurong-west",
    name: "Jurong West",
    region: "West",
    planningArea: "Jurong West",
    tier: 1,
    population: "300,000+",
    constructionCost: { basic: 220, standard: 340, premium: 530 },
    laborCostPerDay: { mason: 135, helper: 78, painter: 118 },
    steelRatePerKg: 1.3,
    cementBagRate: 8.5,
    metaTitle: "Construction Cost & Renovation Answers for Jurong West | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Jurong West, Singapore. Basic from SGD 220/sqft, standard SGD 340/sqft, premium SGD 530/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Sheng Siong Building Materials", "HomeFix", "Selffix", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Jurong Formation with weathered sedimentary rock; suitable for standard strip and pad foundations",
    localTips: [
      "Jurong West has one of the highest HDB concentrations in Singapore — ensure your renovation contractor is on HDB's approved list before signing any contract.",
      "BCA requires all structural modifications to be certified by a Professional Engineer (PE); this includes hacking of walls and floor slab openings.",
      "No renovation work is permitted between 5:30 PM and 9:00 AM; the Jurong-Clementi Town Council actively enforces these restrictions.",
      "Budget for dehumidification solutions and mould-resistant finishes, as the tropical climate can cause rapid deterioration of untreated surfaces.",
    ],
    neighborhoods: ["Boon Lay", "Pioneer", "Nanyang", "Yunnan", "Corporation Drive", "Jurong West Central"],
    nearbyDistrict: "jurong-east",
  },
  {
    slug: "woodlands",
    name: "Woodlands",
    region: "North",
    planningArea: "Woodlands",
    tier: 1,
    population: "250,000+",
    constructionCost: { basic: 210, standard: 330, premium: 520 },
    laborCostPerDay: { mason: 130, helper: 75, painter: 115 },
    steelRatePerKg: 1.2,
    cementBagRate: 8,
    metaTitle: "Construction Cost & Renovation Answers for Woodlands | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Woodlands, Singapore. Basic from SGD 210/sqft, standard SGD 330/sqft, premium SGD 520/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Kansai Paint", "Sheng Siong Building Materials", "HomeFix", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Old Alluvium and Bukit Timah Granite; variable conditions requiring site-specific soil investigation",
    localTips: [
      "Woodlands is undergoing major transformation as the Woodlands Regional Centre — verify URA zoning before planning any A&A (additions and alterations) works.",
      "HDB renovation permits are mandatory; apply at least 3 working days before commencement via the HDB e-Service portal.",
      "Renovation noise restrictions apply from 5:30 PM to 9:00 AM daily — Sembawang Town Council patrols are frequent in this area.",
      "Heavy tropical rainfall in the North region means proper roof waterproofing and gutter systems are essential for landed properties.",
    ],
    neighborhoods: ["Woodlands Central", "Admiralty", "Marsiling", "Woodgrove", "Innova", "Woodlands Ring Road"],
    nearbyDistrict: "ang-mo-kio",
  },
  {
    slug: "sengkang",
    name: "Sengkang",
    region: "North-East",
    planningArea: "Sengkang",
    tier: 1,
    population: "230,000+",
    constructionCost: { basic: 220, standard: 340, premium: 540 },
    laborCostPerDay: { mason: 138, helper: 80, painter: 120 },
    steelRatePerKg: 1.3,
    cementBagRate: 9,
    metaTitle: "Construction Cost & Renovation Answers for Sengkang | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Sengkang, Singapore. Basic from SGD 220/sqft, standard SGD 340/sqft, premium SGD 540/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Sheng Siong Building Materials", "HomeFix", "Kim Hin", "Selffix"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Marine clay and alluvial deposits; proper foundation design critical due to soft ground conditions",
    localTips: [
      "Sengkang's newer HDB developments may have specific renovation guidelines from BCA — check your block's structural limitations before planning wall removal.",
      "HDB renovation permits are required for all works; ensure your contractor submits the application through the proper HDB channels.",
      "Noise restrictions are strictly enforced: no renovation between 5:30 PM and 9:00 AM. The Ang Mo Kio Town Council manages Sengkang estate regulations.",
      "The high water table in parts of Sengkang means ground-floor units should budget extra for damp-proofing and waterproofing measures.",
    ],
    neighborhoods: ["Sengkang Central", "Rivervale", "Compassvale", "Anchorvale", "Fernvale", "Buangkok"],
    nearbyDistrict: "punggol",
  },
  {
    slug: "punggol",
    name: "Punggol",
    region: "North-East",
    planningArea: "Punggol",
    tier: 1,
    population: "200,000+",
    constructionCost: { basic: 230, standard: 350, premium: 550 },
    laborCostPerDay: { mason: 140, helper: 82, painter: 122 },
    steelRatePerKg: 1.35,
    cementBagRate: 9,
    metaTitle: "Construction Cost & Renovation Answers for Punggol | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Punggol, Singapore. Basic from SGD 230/sqft, standard SGD 350/sqft, premium SGD 550/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Dulux", "Sheng Siong Building Materials", "HomeFix", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Reclaimed land and marine clay; specialist foundation solutions may be needed for heavier structures",
    localTips: [
      "Punggol is a designated Eco-Town — BCA Green Mark requirements may apply to certain renovation scopes, especially for newer BTO developments.",
      "HDB renovation permits must be obtained before work begins; the Pasir Ris-Punggol Town Council actively monitors compliance.",
      "No renovation noise between 5:30 PM and 9:00 AM — given Punggol's dense residential layout, neighbours are quick to report violations.",
      "Punggol's reclaimed land areas can experience settlement; consult a structural engineer before making significant load-bearing modifications.",
    ],
    neighborhoods: ["Punggol Central", "Watertown", "Punggol Field", "Punggol Drive", "Matilda", "Northshore", "Punggol Point"],
    nearbyDistrict: "sengkang",
  },
  {
    slug: "clementi",
    name: "Clementi",
    region: "West",
    planningArea: "Clementi",
    tier: 2,
    population: "95,000+",
    constructionCost: { basic: 260, standard: 400, premium: 640 },
    laborCostPerDay: { mason: 155, helper: 88, painter: 140 },
    steelRatePerKg: 1.5,
    cementBagRate: 10,
    metaTitle: "Construction Cost & Renovation Answers for Clementi | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Clementi, Singapore. Basic from SGD 260/sqft, standard SGD 400/sqft, premium SGD 640/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Kansai Paint", "Kim Hin", "Hafary", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Jurong Formation sedimentary rock and Old Alluvium; generally good for construction",
    localTips: [
      "Clementi has a mix of older and newer HDB blocks — older blocks may require additional structural assessment before major renovation works per BCA guidelines.",
      "HDB renovation permits are mandatory; the Jurong-Clementi Town Council has specific guidelines for renovation waste disposal.",
      "Renovation noise restrictions apply from 5:30 PM to 9:00 AM; plan all hacking and drilling work within approved hours.",
      "The proximity to NUS and NTU means high rental demand — renovations aimed at rental yield should focus on durable, low-maintenance finishes suited to tropical weather.",
    ],
    neighborhoods: ["Clementi Central", "Clementi West", "West Coast", "Sunset Way", "Faber", "Clementi Woods"],
    nearbyDistrict: "jurong-east",
  },
  {
    slug: "ang-mo-kio",
    name: "Ang Mo Kio",
    region: "North",
    planningArea: "Ang Mo Kio",
    tier: 2,
    population: "165,000+",
    constructionCost: { basic: 220, standard: 350, premium: 540 },
    laborCostPerDay: { mason: 135, helper: 78, painter: 118 },
    steelRatePerKg: 1.3,
    cementBagRate: 9,
    metaTitle: "Construction Cost & Renovation Answers for Ang Mo Kio | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Ang Mo Kio, Singapore. Basic from SGD 220/sqft, standard SGD 350/sqft, premium SGD 540/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Sheng Siong Building Materials", "HomeFix", "Selffix", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Bukit Timah Granite and Old Alluvium; stable ground with good load-bearing properties",
    localTips: [
      "Many Ang Mo Kio HDB blocks are older estates undergoing SERS or HIP — check with HDB if your block is scheduled for upgrading before investing heavily in renovation.",
      "BCA requires licensed contractors for any structural modification work; always verify your contractor's credentials on BCA's public register.",
      "Noise restrictions from 5:30 PM to 9:00 AM are enforced by the Ang Mo Kio Town Council; repeated violations can result in stop-work orders.",
      "Older blocks may have asbestos-containing materials — engage a BCA-approved specialist for testing before demolition works.",
    ],
    neighborhoods: ["Ang Mo Kio Central", "Kebun Baru", "Cheng San", "Teck Ghee", "Yio Chu Kang"],
    nearbyDistrict: "bishan",
  },
  {
    slug: "bishan",
    name: "Bishan",
    region: "Central",
    planningArea: "Bishan",
    tier: 2,
    population: "90,000+",
    constructionCost: { basic: 280, standard: 430, premium: 680 },
    laborCostPerDay: { mason: 160, helper: 90, painter: 145 },
    steelRatePerKg: 1.5,
    cementBagRate: 10,
    metaTitle: "Construction Cost & Renovation Answers for Bishan | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Bishan, Singapore. Basic from SGD 280/sqft, standard SGD 430/sqft, premium SGD 680/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Dulux", "Kim Hin", "Hafary", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Bukit Timah Granite; excellent bedrock for foundations with minimal settlement risk",
    localTips: [
      "Bishan's central location commands higher property values — invest in quality renovation finishes that meet BCA safety standards to maximise resale potential.",
      "HDB renovation permits are required; Bishan-Toa Payoh Town Council guidelines must be followed for waste disposal and common area usage during renovation.",
      "Renovation noise is restricted between 5:30 PM and 9:00 AM; with Bishan's dense population, strict compliance is essential.",
      "URA guidelines apply to landed properties near Bishan Park — setback and building envelope restrictions may affect your renovation plans.",
    ],
    neighborhoods: ["Bishan East", "Bishan North", "Bishan West", "Upper Thomson", "Sin Ming", "Shunfu"],
    nearbyDistrict: "ang-mo-kio",
  },
  {
    slug: "marina-bay",
    name: "Marina Bay",
    region: "Central",
    planningArea: "Marina South",
    tier: 1,
    population: "10,000+",
    constructionCost: { basic: 400, standard: 650, premium: 1100 },
    laborCostPerDay: { mason: 200, helper: 100, painter: 180 },
    steelRatePerKg: 1.8,
    cementBagRate: 12,
    metaTitle: "Construction Cost & Renovation Answers for Marina Bay | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Marina Bay, Singapore. Basic from SGD 400/sqft, standard SGD 650/sqft, premium SGD 1,100/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Dulux", "Hafary", "Kim Hin", "BMS Building Materials"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Reclaimed land with marine clay substratum; deep piling foundations mandatory for most structures",
    localTips: [
      "Marina Bay properties are predominantly high-end condominiums with strict MCST (Management Corporation Strata Title) renovation rules — obtain written approval before commencing any works.",
      "BCA requires structural assessments for any load-bearing modifications in high-rise buildings; engage an accredited PE for certification.",
      "Renovation noise restrictions of 5:30 PM to 9:00 AM apply; some condominiums impose even stricter hours — check your MCST bylaws.",
      "URA's Marina Bay masterplan includes specific facade and design guidelines; external works must comply with the overall precinct aesthetic.",
    ],
    neighborhoods: ["Marina Bay Financial Centre", "The Sail", "Marina One", "Marina South Pier", "Bayfront"],
    nearbyDistrict: "downtown-core",
  },
  {
    slug: "toa-payoh",
    name: "Toa Payoh",
    region: "Central",
    planningArea: "Toa Payoh",
    tier: 2,
    population: "120,000+",
    constructionCost: { basic: 250, standard: 380, premium: 600 },
    laborCostPerDay: { mason: 148, helper: 85, painter: 130 },
    steelRatePerKg: 1.4,
    cementBagRate: 9.5,
    metaTitle: "Construction Cost & Renovation Answers for Toa Payoh | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Toa Payoh, Singapore. Basic from SGD 250/sqft, standard SGD 380/sqft, premium SGD 600/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Kansai Paint", "Sheng Siong Building Materials", "HomeFix", "Kim Hin"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Kallang Formation marine clay over Old Alluvium; ground improvement may be needed for heavier loads",
    localTips: [
      "Toa Payoh is one of Singapore's oldest HDB estates — many blocks are eligible for HIP (Home Improvement Programme). Check HDB's schedule to avoid duplicating works covered by HIP.",
      "BCA mandates that hacking of any structural element requires a Professional Engineer's endorsement and prior HDB approval.",
      "Renovation work must stop between 5:30 PM and 9:00 AM; the Bishan-Toa Payoh Town Council conducts regular enforcement checks.",
      "Older plumbing in Toa Payoh blocks may use galvanised iron pipes — budget for full pipe replacement with copper or PVC during major renovations.",
    ],
    neighborhoods: ["Toa Payoh Central", "Toa Payoh East", "Toa Payoh West", "Lorong 1 to 8", "Kim Keat", "Potong Pasir border"],
    nearbyDistrict: "bishan",
  },
  {
    slug: "hougang",
    name: "Hougang",
    region: "North-East",
    planningArea: "Hougang",
    tier: 2,
    population: "185,000+",
    constructionCost: { basic: 220, standard: 340, premium: 530 },
    laborCostPerDay: { mason: 135, helper: 78, painter: 118 },
    steelRatePerKg: 1.3,
    cementBagRate: 8.5,
    metaTitle: "Construction Cost & Renovation Answers for Hougang | Biddaro",
    metaDescription:
      "Get accurate construction and renovation costs for Hougang, Singapore. Basic from SGD 220/sqft, standard SGD 340/sqft, premium SGD 530/sqft. Compare contractor rates and material prices.",
    localBrands: ["Nippon Paint", "Sheng Siong Building Materials", "HomeFix", "Selffix", "Hoe Kee Hardware"],
    climateType: "Tropical equatorial; high humidity year-round with average temperatures of 25-32°C",
    soilType: "Old Alluvium with pockets of marine clay; standard raft foundations generally sufficient",
    localTips: [
      "Hougang has a large number of DBSS (Design, Build and Sell Scheme) flats with specific renovation restrictions — verify your unit type before planning structural changes per BCA rules.",
      "HDB renovation permits are required; the Aljunied-Hougang Town Council has specific guidelines on disposal chutes and common corridor usage during renovation.",
      "No renovation noise between 5:30 PM and 9:00 AM — the town council responds swiftly to noise complaints, so communicate your renovation schedule to neighbours in advance.",
      "Tropical weather causes rapid algae and mould growth on external surfaces — use anti-fungal exterior paints and ensure proper ventilation in all wet areas.",
    ],
    neighborhoods: ["Hougang Central", "Kovan", "Lorong Ah Soo", "Defu", "Upper Serangoon", "Hougang Avenue"],
    nearbyDistrict: "sengkang",
  },
];

export function getSGCityBySlug(slug: string): SGCityData | undefined {
  return SG_CITIES.find((c) => c.slug === slug);
}
