// lib/ask-city-data.ts
// 30 Indian city profiles for /ask/city/[city]/[slug] programmatic SEO pages

export interface CityData {
  slug: string;
  name: string;
  state: string;
  region: 'west' | 'north' | 'south' | 'east' | 'central';
  tier: 1 | 2 | 3;
  population: string;
  constructionCost: { basic: number; standard: number; premium: number }; // ₹ per sqft
  laborCostPerDay: { mason: number; helper: number; painter: number };
  steelRatePerKg: number;
  cementBagRate: number;
  metaTitle: string;
  metaDescription: string;
  localBrands: string[];
  climateType: string;
  soilType: string;
  localTips: string[];
  neighborhoods: string[];
  nearbyCity?: string;
}

export const CITIES: CityData[] = [
  {
    slug: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    region: 'west',
    tier: 1,
    population: '21M+',
    constructionCost: { basic: 2200, standard: 2800, premium: 4500 },
    laborCostPerDay: { mason: 900, helper: 600, painter: 850 },
    steelRatePerKg: 72,
    cementBagRate: 400,
    metaTitle: 'Construction Cost & Home Renovation Answers for Mumbai | Biddaro',
    metaDescription: 'Mumbai construction costs 2024: ₹2,200-4,500/sqft. City-specific answers on building costs, contractors, Vastu, materials for Bandra, Andheri, Thane areas.',
    localBrands: ['UltraTech', 'Asian Paints', 'Kajaria', 'Dr. Fixit', 'Pidilite'],
    climateType: 'Tropical, high humidity, heavy monsoon (2,500mm+)',
    soilType: 'Basalt rock, black cotton soil in suburbs',
    localTips: [
      'Mumbai\'s heavy monsoon (June-Sept) demands Grade-1 waterproofing — budget ₹80-120/sqft extra for terrace + walls',
      'AAC blocks instead of red bricks reduce dead load in Mumbai\'s seismic zone (Zone III) — saves 15% on structure',
      'Construction ban during monsoon peak: notify your contractor to complete RCC work before June 15',
      'Bandra/Worli have strict BMC height restrictions — verify FSI before finalizing your plan',
    ],
    neighborhoods: ['Bandra', 'Andheri', 'Thane', 'Borivali', 'Dadar', 'Kurla', 'Powai'],
    nearbyCity: 'navi-mumbai',
  },
  {
    slug: 'delhi',
    name: 'Delhi',
    state: 'Delhi NCT',
    region: 'north',
    tier: 1,
    population: '32M+',
    constructionCost: { basic: 1800, standard: 2400, premium: 4000 },
    laborCostPerDay: { mason: 800, helper: 550, painter: 750 },
    steelRatePerKg: 70,
    cementBagRate: 390,
    metaTitle: 'Construction Cost & Home Renovation Answers for Delhi | Biddaro',
    metaDescription: 'Delhi construction costs 2024: ₹1,800-4,000/sqft. Expert answers on building, renovation, contractor hiring for South Delhi, Dwarka, Rohini areas.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Somany Tiles', 'Havells'],
    climateType: 'Semi-arid, extreme heat (47°C) in summer, cold winters, moderate monsoon',
    soilType: 'Alluvial soil, good bearing capacity in most areas',
    localTips: [
      'Delhi\'s extreme summer (45°C+) requires AAC blocks + roof insulation — saves 30% on cooling costs',
      'DDA floor plans must be strictly followed — illegal construction faces demolition drives',
      'Winter construction (Dec-Jan): curing concrete needs blankets/hot water — add ₹5,000-10,000 to budget',
      'South Delhi areas have rocky sub-soil — foundation excavation costs 20% higher than average',
    ],
    neighborhoods: ['South Delhi', 'Dwarka', 'Rohini', 'Pitampura', 'Lajpat Nagar', 'Vasant Kunj'],
  },
  {
    slug: 'bangalore',
    name: 'Bangalore',
    state: 'Karnataka',
    region: 'south',
    tier: 1,
    population: '14M+',
    constructionCost: { basic: 1800, standard: 2500, premium: 4200 },
    laborCostPerDay: { mason: 850, helper: 580, painter: 800 },
    steelRatePerKg: 71,
    cementBagRate: 395,
    metaTitle: 'Construction Cost & Home Renovation Answers for Bangalore | Biddaro',
    metaDescription: 'Bangalore construction costs 2024: ₹1,800-4,200/sqft. Answers on building, Vastu, contractor hiring for Whitefield, Jayanagar, Sarjapur areas.',
    localBrands: ['UltraTech', 'Ramco Cement', 'Asian Paints', 'Kajaria', 'Dr. Fixit'],
    climateType: 'Pleasant (18-35°C), mild monsoon, moderate humidity',
    soilType: 'Hard rock in many areas, red laterite soil in outskirts',
    localTips: [
      'Bangalore\'s rocky sub-soil means higher excavation costs — budget ₹1.5-3L extra for rock-cutting in Whitefield/Koramangala',
      'BBMP regulations strictly enforce setback rules — maintain 3m front, 1.5m side setback',
      'Good climate means minimal insulation needed — but invest in good waterproofing for north-facing walls',
      'Contractor availability is tight in peak season (Oct-Feb) — book 3 months in advance',
    ],
    neighborhoods: ['Whitefield', 'Jayanagar', 'Sarjapur', 'Koramangala', 'HSR Layout', 'JP Nagar', 'Hebbal'],
  },
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    region: 'south',
    tier: 1,
    population: '10M+',
    constructionCost: { basic: 1600, standard: 2200, premium: 3600 },
    laborCostPerDay: { mason: 750, helper: 520, painter: 720 },
    steelRatePerKg: 69,
    cementBagRate: 385,
    metaTitle: 'Construction Cost & Home Renovation Answers for Hyderabad | Biddaro',
    metaDescription: 'Hyderabad construction costs 2024: ₹1,600-3,600/sqft. Expert answers for Gachibowli, Banjara Hills, Kondapur areas. Best contractors & materials.',
    localBrands: ['Ramco Cement', 'UltraTech', 'Asian Paints', 'RAK Tiles', 'Dr. Fixit'],
    climateType: 'Hot semi-arid, dry summers (42°C), mild monsoon',
    soilType: 'Granite rock in HITEC City area, black cotton soil in old city',
    localTips: [
      'Hyderabad\'s granite rock sub-soil makes foundation work expensive in Gachibowli/Kondapur — budget ₹2L extra',
      'HMDA and GHMC have different setback rules — verify your plot\'s zone before starting',
      'Hot dry summers require thermal insulation in roof — 75mm EPS board saves ₹20-30K annually on AC bills',
      'Old city areas have high water table — RCC raft foundation recommended over isolated footings',
    ],
    neighborhoods: ['Gachibowli', 'Banjara Hills', 'Kondapur', 'Kukatpally', 'Madhapur', 'Secunderabad'],
  },
  {
    slug: 'chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    region: 'south',
    tier: 1,
    population: '11M+',
    constructionCost: { basic: 1700, standard: 2300, premium: 3800 },
    laborCostPerDay: { mason: 780, helper: 540, painter: 740 },
    steelRatePerKg: 70,
    cementBagRate: 388,
    metaTitle: 'Construction Cost & Home Renovation Answers for Chennai | Biddaro',
    metaDescription: 'Chennai construction costs 2024: ₹1,700-3,800/sqft. Expert answers for Adyar, Anna Nagar, OMR areas. Monsoon-proof construction tips.',
    localBrands: ['Ramco Cement', 'India Cements', 'Asian Paints', 'Kajaria', 'Berger Paints'],
    climateType: 'Tropical wet, hot humid, northeast monsoon (Oct-Dec)',
    soilType: 'Sandy soil near coast, clay in interior areas — high water table near sea',
    localTips: [
      'Chennai\'s northeast monsoon (Oct-Dec) is different from rest of India — plan construction pause accordingly',
      'High humidity demands anti-fungal paint (at least 2 coats) on all external walls',
      'OMR and ECR areas have high water table — provide waterproofing up to 1.2m height from ground level',
      'CMDA setback rules are strict — 3m front setback mandatory for plots above 250 sqm',
    ],
    neighborhoods: ['Adyar', 'Anna Nagar', 'OMR', 'Velachery', 'Porur', 'Chromepet', 'Tambaram'],
  },
  {
    slug: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    region: 'east',
    tier: 1,
    population: '15M+',
    constructionCost: { basic: 1500, standard: 2000, premium: 3200 },
    laborCostPerDay: { mason: 720, helper: 500, painter: 680 },
    steelRatePerKg: 68,
    cementBagRate: 380,
    metaTitle: 'Construction Cost & Home Renovation Answers for Kolkata | Biddaro',
    metaDescription: 'Kolkata construction costs 2024: ₹1,500-3,200/sqft. Answers for Salt Lake, New Town, Howrah areas. Monsoon waterproofing & local tips.',
    localBrands: ['ACC Cement', 'UltraTech', 'Berger Paints', 'Somany Tiles', 'Finolex'],
    climateType: 'Tropical wet, very high humidity, heavy monsoon',
    soilType: 'Alluvial deposit, soft silty clay — very poor bearing capacity near river',
    localTips: [
      'Kolkata\'s soft alluvial soil requires pile foundation for G+2 and above — adds ₹5-8L to foundation cost',
      'Very high humidity means external walls need anti-fungal, moisture-resistant paint every 3-4 years',
      'KMC (Kolkata Municipal Corporation) approval takes 3-6 months — start early',
      'Salt Lake sector plots have strict height limits of G+2 — check before planning an extra floor',
    ],
    neighborhoods: ['Salt Lake', 'New Town', 'Howrah', 'Rajarhat', 'Ballygunge', 'Behala'],
  },
  {
    slug: 'pune',
    name: 'Pune',
    state: 'Maharashtra',
    region: 'west',
    tier: 1,
    population: '7M+',
    constructionCost: { basic: 1700, standard: 2300, premium: 3800 },
    laborCostPerDay: { mason: 800, helper: 560, painter: 760 },
    steelRatePerKg: 71,
    cementBagRate: 392,
    metaTitle: 'Construction Cost & Home Renovation Answers for Pune | Biddaro',
    metaDescription: 'Pune construction costs 2024: ₹1,700-3,800/sqft. Expert answers for Hinjewadi, Kothrud, Wakad areas. Local contractor tips & material guides.',
    localBrands: ['UltraTech', 'Asian Paints', 'Kajaria', 'Dr. Fixit', 'Pidilite'],
    climateType: 'Semi-arid, pleasant year-round (15-36°C), moderate monsoon',
    soilType: 'Basalt rock in many areas, black cotton soil in Hadapsar/Undri',
    localTips: [
      'Pune\'s Hinjewadi IT corridor has expensive labor due to high demand — get 3 quotes before finalizing',
      'PMC and PCMC have different building bylaws — verify your plot\'s jurisdiction',
      'Black cotton soil areas (Undri, Hadapsar) require deeper foundation — budget ₹2-3L extra',
      'Moderate climate = no extra insulation needed, but invest in good ventilation design',
    ],
    neighborhoods: ['Hinjewadi', 'Kothrud', 'Wakad', 'Baner', 'Hadapsar', 'Viman Nagar', 'Aundh'],
  },
  {
    slug: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    region: 'west',
    tier: 1,
    population: '8M+',
    constructionCost: { basic: 1500, standard: 2100, premium: 3400 },
    laborCostPerDay: { mason: 740, helper: 510, painter: 700 },
    steelRatePerKg: 69,
    cementBagRate: 382,
    metaTitle: 'Construction Cost & Home Renovation Answers for Ahmedabad | Biddaro',
    metaDescription: 'Ahmedabad construction costs 2024: ₹1,500-3,400/sqft. Expert answers for SG Highway, Bopal, Prahlad Nagar areas. Gujarat-specific building tips.',
    localBrands: ['UltraTech', 'Nuvoco Cement', 'Asian Paints', 'Nitco Tiles', 'Polycab'],
    climateType: 'Hot semi-arid, extreme heat (46°C) in summer, very dry',
    soilType: 'Alluvial soil with good bearing capacity, some clay pockets',
    localTips: [
      'Ahmedabad\'s extreme dry heat requires excellent thermal insulation — 100mm hollow block outer walls + insulation',
      'AUDA and AMC have different DCR rules — check your zone before starting',
      'Seismic Zone III — earthquake-resistant RCC frame is mandatory; do not cut corners on columns',
      'Very dry climate means less waterproofing needed compared to coastal cities — but terrace must be done well',
    ],
    neighborhoods: ['SG Highway', 'Bopal', 'Prahlad Nagar', 'Satellite', 'Thaltej', 'Maninagar'],
  },
  {
    slug: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    region: 'north',
    tier: 2,
    population: '4M+',
    constructionCost: { basic: 1400, standard: 1900, premium: 3000 },
    laborCostPerDay: { mason: 700, helper: 480, painter: 660 },
    steelRatePerKg: 68,
    cementBagRate: 378,
    metaTitle: 'Construction Cost & Home Renovation Answers for Jaipur | Biddaro',
    metaDescription: 'Jaipur construction costs 2024: ₹1,400-3,000/sqft. Expert answers for Malviya Nagar, Vaishali Nagar, Jagatpura areas. Rajasthani stone & local tips.',
    localBrands: ['UltraTech', 'Birla White', 'Asian Paints', 'Kajaria', 'Kota Stone'],
    climateType: 'Hot semi-arid, extreme summer (45°C), very cold winter, minimal rain',
    soilType: 'Sandy and rocky, good bearing capacity, sand dune areas in north',
    localTips: [
      'Jaipur\'s iconic Dholpur/Kota stone is locally available at lower cost — use for flooring to reduce costs',
      'Extreme temperature swings (0°C winter to 45°C summer) — use double-brick walls for natural insulation',
      'JDA setback and height rules vary by zone — Vaishali Nagar has stricter limits than outskirts',
      'Very dry climate — minimal waterproofing needed, but AC unit drainage waterproofing is important',
    ],
    neighborhoods: ['Malviya Nagar', 'Vaishali Nagar', 'Jagatpura', 'Mansarovar', 'C-Scheme', 'Tonk Road'],
  },
  {
    slug: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    region: 'north',
    tier: 2,
    population: '3.5M+',
    constructionCost: { basic: 1300, standard: 1800, premium: 2800 },
    laborCostPerDay: { mason: 680, helper: 460, painter: 640 },
    steelRatePerKg: 67,
    cementBagRate: 375,
    metaTitle: 'Construction Cost & Home Renovation Answers for Lucknow | Biddaro',
    metaDescription: 'Lucknow construction costs 2024: ₹1,300-2,800/sqft. Expert answers for Gomti Nagar, Hazratganj, Aliganj areas. UP RERA-compliant contractor tips.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Somany Tiles', 'Havells'],
    climateType: 'Semi-arid, very hot summer (44°C), cold foggy winter, moderate monsoon',
    soilType: 'Alluvial Gangetic plain soil, moderate bearing capacity',
    localTips: [
      'LDA (Lucknow Development Authority) approval is mandatory — plan 3-4 months for approvals',
      'Gangetic alluvial soil has moderate bearing capacity — isolated RCC footings work fine for G+2',
      'Cold foggy winters (Dec-Jan) slow concrete curing — use warm water and jute covers for curing',
      'Gomti Nagar extension has high water table — provide 1m waterproofing above ground level',
    ],
    neighborhoods: ['Gomti Nagar', 'Hazratganj', 'Aliganj', 'Rajajipuram', 'Indira Nagar', 'Alambagh'],
  },
  {
    slug: 'chandigarh',
    name: 'Chandigarh',
    state: 'Chandigarh UT',
    region: 'north',
    tier: 2,
    population: '1.2M+',
    constructionCost: { basic: 1600, standard: 2200, premium: 3500 },
    laborCostPerDay: { mason: 780, helper: 540, painter: 740 },
    steelRatePerKg: 70,
    cementBagRate: 390,
    metaTitle: 'Construction Cost & Home Renovation Answers for Chandigarh | Biddaro',
    metaDescription: 'Chandigarh construction costs 2024: ₹1,600-3,500/sqft. Expert answers for Sector 17, Panchkula, Mohali areas. Chandigarh building bylaws & tips.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Nitco Tiles', 'Polycab'],
    climateType: 'Humid subtropical, very cold winters, hot dry summers',
    soilType: 'Alluvial plains with good bearing capacity',
    localTips: [
      'Chandigarh\'s heritage zone has strict height and architectural style restrictions — mandatory Corbusier-style setbacks',
      'Sector plots have fixed FAR — no extra floors allowed without special permission',
      'Panchkula (Haryana) and Mohali (Punjab) have different building regulations than UT — confirm your zone',
      'Cold winters need double-glazed windows — adds ₹1-2L but saves on heating costs',
    ],
    neighborhoods: ['Sector 17', 'Sector 22', 'Panchkula', 'Mohali', 'Zirakpur', 'Aerocity'],
  },
  {
    slug: 'kochi',
    name: 'Kochi',
    state: 'Kerala',
    region: 'south',
    tier: 2,
    population: '2.1M+',
    constructionCost: { basic: 1700, standard: 2400, premium: 3900 },
    laborCostPerDay: { mason: 900, helper: 620, painter: 860 },
    steelRatePerKg: 72,
    cementBagRate: 398,
    metaTitle: 'Construction Cost & Home Renovation Answers for Kochi | Biddaro',
    metaDescription: 'Kochi construction costs 2024: ₹1,700-3,900/sqft. Expert answers for Edappally, Kakkanad, Marine Drive areas. Kerala traditional & modern construction tips.',
    localBrands: ['Malabar Cements', 'Ramco', 'Asian Paints', 'Kalzip', 'Dr. Fixit'],
    climateType: 'Tropical, very high humidity, two monsoons (June-Aug, Oct-Nov), 3,000mm+ rain',
    soilType: 'Laterite rock common, alluvial coastal areas, high water table near backwaters',
    localTips: [
      'Kerala\'s double monsoon makes waterproofing critical — budget ₹150-200/sqft for comprehensive coverage',
      'Labor in Kerala is highly skilled but expensive — mason rates are 20% higher than national average',
      'Traditional Nalukettu design requires specialist masons — premium of ₹200-400/sqft over standard RCC',
      'Laterite stone (Kallummai) is locally available and excellent for low-cost walls — saves 15% on walling cost',
    ],
    neighborhoods: ['Edappally', 'Kakkanad', 'Marine Drive', 'Aluva', 'Thrippunithura', 'Perumbavoor'],
  },
  {
    slug: 'nagpur',
    name: 'Nagpur',
    state: 'Maharashtra',
    region: 'central',
    tier: 2,
    population: '2.9M+',
    constructionCost: { basic: 1400, standard: 1900, premium: 3000 },
    laborCostPerDay: { mason: 720, helper: 490, painter: 680 },
    steelRatePerKg: 69,
    cementBagRate: 382,
    metaTitle: 'Construction Cost & Home Renovation Answers for Nagpur | Biddaro',
    metaDescription: 'Nagpur construction costs 2024: ₹1,400-3,000/sqft. Expert answers for Dharampeth, Ramdaspeth, MIHAN areas. NMC building rules & local contractor guide.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Kajaria', 'Finolex'],
    climateType: 'Tropical wet and dry, extreme heat (48°C) in May, dry summers',
    soilType: 'Black cotton soil throughout — shrinks in dry season, swells in monsoon',
    localTips: [
      'Nagpur\'s black cotton soil expands and contracts — raft foundation is strongly recommended for any construction',
      'Extreme heat (48°C in May) — white or light-colored roof coating essential, saves 5°C indoors',
      'NMC approval process is relatively fast compared to other metros — typically 30-45 days for residential',
      'Orange City has affordable skilled labor — good for renovation projects at lower cost than Mumbai/Pune',
    ],
    neighborhoods: ['Dharampeth', 'Ramdaspeth', 'MIHAN', 'Sadar', 'Trimurti Nagar', 'Manish Nagar'],
  },
  {
    slug: 'indore',
    name: 'Indore',
    state: 'Madhya Pradesh',
    region: 'central',
    tier: 2,
    population: '3.3M+',
    constructionCost: { basic: 1300, standard: 1800, premium: 2800 },
    laborCostPerDay: { mason: 680, helper: 460, painter: 640 },
    steelRatePerKg: 67,
    cementBagRate: 375,
    metaTitle: 'Construction Cost & Home Renovation Answers for Indore | Biddaro',
    metaDescription: 'Indore construction costs 2024: ₹1,300-2,800/sqft. Expert answers for Vijay Nagar, Scheme 140, Rau areas. MP RERA tips & local contractor guide.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Somany Tiles', 'Polycab'],
    climateType: 'Semi-arid highland, mild pleasant climate, moderate monsoon',
    soilType: 'Black cotton soil in most areas, murram in higher areas',
    localTips: [
      'Indore\'s pleasant climate (avg 24°C) means minimal insulation needed — save on AC costs with good orientation',
      'Black cotton soil = mandatory raft foundation or deep isolated footings to 8 feet depth',
      'IDA (Indore Development Authority) approval required — takes 30-45 days',
      'Fastest growing construction market in MP — material prices are competitive, good contractor availability',
    ],
    neighborhoods: ['Vijay Nagar', 'Scheme 140', 'Rau', 'Palasia', 'Bhawarkuan', 'Super Corridor'],
  },
  {
    slug: 'surat',
    name: 'Surat',
    state: 'Gujarat',
    region: 'west',
    tier: 2,
    population: '6.5M+',
    constructionCost: { basic: 1400, standard: 1900, premium: 3000 },
    laborCostPerDay: { mason: 720, helper: 490, painter: 680 },
    steelRatePerKg: 68,
    cementBagRate: 380,
    metaTitle: 'Construction Cost & Home Renovation Answers for Surat | Biddaro',
    metaDescription: 'Surat construction costs 2024: ₹1,400-3,000/sqft. Expert answers for Vesu, Adajan, Althan areas. SMCP building rules & local contractor guide.',
    localBrands: ['UltraTech', 'Nuvoco', 'Asian Paints', 'Nitco Tiles', 'Polycab'],
    climateType: 'Tropical wet and dry, hot humid, heavy monsoon, flood-prone',
    soilType: 'Alluvial silty clay from river, some rocky patches in outskirts',
    localTips: [
      'Surat is flood-prone (Tapi river) — build ground floor plinth at min 0.9m above road level',
      'Diamond and textile industry wealth drives premium demand — finishing quality expectations are high',
      'SMCP (Surat Municipal Corporation) building permission is digital and relatively fast',
      'Humid climate requires anti-fungal paint on all walls — add ₹15/sqft to paint budget',
    ],
    neighborhoods: ['Vesu', 'Adajan', 'Althan', 'Piplod', 'Katargam', 'Udhna'],
  },
  {
    slug: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    region: 'south',
    tier: 2,
    population: '2.4M+',
    constructionCost: { basic: 1400, standard: 1900, premium: 3000 },
    laborCostPerDay: { mason: 730, helper: 500, painter: 700 },
    steelRatePerKg: 69,
    cementBagRate: 384,
    metaTitle: 'Construction Cost & Home Renovation Answers for Visakhapatnam | Biddaro',
    metaDescription: 'Vizag construction costs 2024: ₹1,400-3,000/sqft. Expert answers for Gajuwaka, MVP Colony, Rushikonda areas. Coastal construction tips.',
    localBrands: ['Ramco Cement', 'India Cements', 'Asian Paints', 'Kajaria', 'Dr. Fixit'],
    climateType: 'Tropical wet, coastal humidity, cyclone-prone (Oct-Dec)',
    soilType: 'Rocky hilly terrain, sandy coastal areas, alluvial plains',
    localTips: [
      'Coastal location means cyclone-resistant construction is essential — all roof connections must be hurricane-strapped',
      'Salt-laden sea breeze causes rebar corrosion — use epoxy-coated or stainless steel rebar within 500m of coast',
      'VUDA approval process has improved — allow 45-60 days for residential approval',
      'Rocky terrain in hills requires blasting for foundation — adds ₹3-5L to budget in hilly areas',
    ],
    neighborhoods: ['Gajuwaka', 'MVP Colony', 'Rushikonda', 'Steel Plant Area', 'Lawsons Bay', 'Madhurawada'],
  },
  {
    slug: 'bhopal',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    region: 'central',
    tier: 2,
    population: '2.4M+',
    constructionCost: { basic: 1200, standard: 1700, premium: 2700 },
    laborCostPerDay: { mason: 660, helper: 450, painter: 620 },
    steelRatePerKg: 67,
    cementBagRate: 372,
    metaTitle: 'Construction Cost & Home Renovation Answers for Bhopal | Biddaro',
    metaDescription: 'Bhopal construction costs 2024: ₹1,200-2,700/sqft. Expert answers for Arera Colony, Kolar Road, Hoshangabad Road. Local tips & contractor guide.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Johnson Tiles', 'Finolex'],
    climateType: 'Tropical wet and dry highland, mild climate, moderate monsoon',
    soilType: 'Black cotton soil and rocky patches at higher elevations',
    localTips: [
      'Bhopal\'s hilly terrain can mean uneven sub-soil — get soil testing done (costs ₹5,000-10,000) before starting',
      'Black cotton soil in low-lying areas — deep foundation or raft mandatory',
      'Capital city infrastructure means good material availability and reasonable contractor costs',
      'BHEL township and government colony areas have additional approval requirements from authorities',
    ],
    neighborhoods: ['Arera Colony', 'Kolar Road', 'Hoshangabad Road', 'Shyamla Hills', 'Ayodhya Bypass', 'Misrod'],
  },
  {
    slug: 'coimbatore',
    name: 'Coimbatore',
    state: 'Tamil Nadu',
    region: 'south',
    tier: 2,
    population: '2.2M+',
    constructionCost: { basic: 1500, standard: 2000, premium: 3200 },
    laborCostPerDay: { mason: 760, helper: 520, painter: 720 },
    steelRatePerKg: 70,
    cementBagRate: 386,
    metaTitle: 'Construction Cost & Home Renovation Answers for Coimbatore | Biddaro',
    metaDescription: 'Coimbatore construction costs 2024: ₹1,500-3,200/sqft. Expert answers for Saravanampatti, RS Puram, Peelamedu areas. Local contractor tips.',
    localBrands: ['Ramco Cement', 'India Cements', 'Asian Paints', 'Kajaria', 'Polycab'],
    climateType: 'Semi-arid, pleasant year-round (20-38°C), moderate rainfall',
    soilType: 'Red sandy loam in most areas, good bearing capacity',
    localTips: [
      'Coimbatore\'s textile industry means high disposable income — quality finishing expectations are above-average',
      'Pleasant climate needs no special insulation — focus budget on quality materials and finish',
      'CMDA (Coimbatore Metropolitan DA) has clear guidelines — approval typically within 45 days',
      'Groundwater level is high in many areas — provide basement waterproofing even for ground floor',
    ],
    neighborhoods: ['Saravanampatti', 'RS Puram', 'Peelamedu', 'Singanallur', 'Ganapathy', 'Vadavalli'],
  },
  {
    slug: 'noida',
    name: 'Noida',
    state: 'Uttar Pradesh',
    region: 'north',
    tier: 2,
    population: '0.7M+',
    constructionCost: { basic: 1700, standard: 2300, premium: 3800 },
    laborCostPerDay: { mason: 800, helper: 550, painter: 760 },
    steelRatePerKg: 70,
    cementBagRate: 390,
    metaTitle: 'Construction Cost & Home Renovation Answers for Noida | Biddaro',
    metaDescription: 'Noida construction costs 2024: ₹1,700-3,800/sqft. Expert answers for Sector 137, 150, Greater Noida areas. NOIDA Authority building rules.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Somany Tiles', 'Havells'],
    climateType: 'Semi-arid, very hot summer (44°C), cold foggy winter, moderate monsoon',
    soilType: 'Alluvial Yamuna flood plain, moderate bearing capacity',
    localTips: [
      'Noida Authority building approval is online and faster than UP municipalities — typically 45-60 days',
      'Greater Noida and Noida Extension have different authorities — verify your plot jurisdiction',
      'Foggy cold winters (Dec-Jan) require curing blankets for fresh concrete — add ₹5,000 to budget',
      'High water table in sectors near Yamuna — waterproof plinth upto 1.5m from ground level',
    ],
    neighborhoods: ['Sector 137', 'Sector 150', 'Greater Noida West', 'Sector 62', 'Sector 18', 'Yamuna Expressway'],
  },
  {
    slug: 'gurgaon',
    name: 'Gurgaon',
    state: 'Haryana',
    region: 'north',
    tier: 2,
    population: '1.5M+',
    constructionCost: { basic: 1900, standard: 2600, premium: 4200 },
    laborCostPerDay: { mason: 850, helper: 580, painter: 800 },
    steelRatePerKg: 71,
    cementBagRate: 393,
    metaTitle: 'Construction Cost & Home Renovation Answers for Gurgaon | Biddaro',
    metaDescription: 'Gurgaon construction costs 2024: ₹1,900-4,200/sqft. Expert answers for DLF, Sohna Road, Golf Course Road areas. DTCP & MCG building rules.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Kajaria', 'Havells'],
    climateType: 'Semi-arid, extreme heat (45°C), cold winters, moderate monsoon',
    soilType: 'Alluvial with some rocky patches in Aravalli range areas',
    localTips: [
      'MCG and DTCP have separate jurisdictions — plot in New Gurgaon vs old city follow different rules',
      'Aravalli range plots may be in eco-sensitive zone — verify with DTCP before buying/building',
      'Extremely competitive contractor market — get minimum 3 quotes as prices vary widely',
      'High-end IT corridors demand premium-quality finishing — clients expect marble, branded tiles, premium paint',
    ],
    neighborhoods: ['DLF Phase 1-5', 'Sohna Road', 'Golf Course Road', 'New Gurgaon', 'Sector 57', 'Manesar'],
  },
  {
    slug: 'navi-mumbai',
    name: 'Navi Mumbai',
    state: 'Maharashtra',
    region: 'west',
    tier: 2,
    population: '1.2M+',
    constructionCost: { basic: 2100, standard: 2700, premium: 4300 },
    laborCostPerDay: { mason: 880, helper: 590, painter: 840 },
    steelRatePerKg: 72,
    cementBagRate: 400,
    metaTitle: 'Construction Cost & Home Renovation Answers for Navi Mumbai | Biddaro',
    metaDescription: 'Navi Mumbai construction costs 2024: ₹2,100-4,300/sqft. Expert answers for Kharghar, Vashi, Panvel areas. NMMC & CIDCO building approval guide.',
    localBrands: ['UltraTech', 'Asian Paints', 'Kajaria', 'Dr. Fixit', 'Pidilite'],
    climateType: 'Tropical coastal, high humidity, very heavy monsoon (3,000mm+)',
    soilType: 'Reclaimed land in many areas, rocky sub-soil in elevated areas',
    localTips: [
      'CIDCO plots have different FSI rules than NMMC areas — verify your plot\'s governing authority',
      'Reclaimed low-lying areas (near creek) have very poor soil — pile foundation is mandatory',
      'Same monsoon intensity as Mumbai — full waterproofing budget is essential (₹80-120/sqft)',
      'Kharghar hills have rocky sub-soil — blasting may be needed for foundation, adds ₹2-4L',
    ],
    neighborhoods: ['Kharghar', 'Vashi', 'Panvel', 'Belapur', 'Nerul', 'Airoli', 'Ulwe'],
    nearbyCity: 'mumbai',
  },
  {
    slug: 'thane',
    name: 'Thane',
    state: 'Maharashtra',
    region: 'west',
    tier: 2,
    population: '1.9M+',
    constructionCost: { basic: 2000, standard: 2600, premium: 4100 },
    laborCostPerDay: { mason: 870, helper: 585, painter: 830 },
    steelRatePerKg: 72,
    cementBagRate: 400,
    metaTitle: 'Construction Cost & Home Renovation Answers for Thane | Biddaro',
    metaDescription: 'Thane construction costs 2024: ₹2,000-4,100/sqft. Expert answers for Ghodbunder Road, Hiranandani, Majiwada areas. TMC building approval guide.',
    localBrands: ['UltraTech', 'Asian Paints', 'Kajaria', 'Dr. Fixit', 'Pidilite'],
    climateType: 'Tropical, high humidity, heavy monsoon (Mumbai levels)',
    soilType: 'Rocky basalt in eastern areas, alluvial near creek areas',
    localTips: [
      'TMC (Thane Municipal Corporation) approval is faster than BMC — typically 2-3 months vs 4-6 months',
      'Creek-facing plots have marshy sub-soil — get soil test done, expect pile foundation costs',
      'Ghodbunder Road area is growing fast — good contractor availability but prices rising',
      'Same monsoon waterproofing requirements as Mumbai — do not compromise on terrace waterproofing',
    ],
    neighborhoods: ['Ghodbunder Road', 'Hiranandani Estate', 'Majiwada', 'Pokhran Road', 'Manpada', 'Vartak Nagar'],
    nearbyCity: 'mumbai',
  },
  {
    slug: 'mysore',
    name: 'Mysore',
    state: 'Karnataka',
    region: 'south',
    tier: 2,
    population: '1.0M+',
    constructionCost: { basic: 1400, standard: 1900, premium: 3000 },
    laborCostPerDay: { mason: 750, helper: 510, painter: 710 },
    steelRatePerKg: 70,
    cementBagRate: 386,
    metaTitle: 'Construction Cost & Home Renovation Answers for Mysore | Biddaro',
    metaDescription: 'Mysore construction costs 2024: ₹1,400-3,000/sqft. Expert answers for Vijayanagar, Kuvempunagar, Hebbal areas. MCC building approval guide.',
    localBrands: ['Ramco Cement', 'UltraTech', 'Asian Paints', 'Kajaria', 'Polycab'],
    climateType: 'Tropical, pleasant year-round (15-33°C), moderate monsoon',
    soilType: 'Red laterite in most areas, good bearing capacity',
    localTips: [
      'MCC (Mysore City Corporation) approvals are straightforward — plan 30-45 days',
      'Lower cost than Bangalore by 20-30% — good option for retirement homes or second homes',
      'Pleasant climate needs minimal insulation or AC investment — design for natural ventilation',
      'Strong heritage architecture tradition — specialist masons for traditional Mysore-style homes available',
    ],
    neighborhoods: ['Vijayanagar', 'Kuvempunagar', 'Hebbal', 'Saraswathipuram', 'Dattagalli', 'Hinkal'],
  },
  {
    slug: 'nashik',
    name: 'Nashik',
    state: 'Maharashtra',
    region: 'west',
    tier: 2,
    population: '1.7M+',
    constructionCost: { basic: 1300, standard: 1800, premium: 2900 },
    laborCostPerDay: { mason: 700, helper: 480, painter: 660 },
    steelRatePerKg: 70,
    cementBagRate: 389,
    metaTitle: 'Construction Cost & Home Renovation Answers for Nashik | Biddaro',
    metaDescription: 'Nashik construction costs 2024: ₹1,300-2,900/sqft. Expert answers for Gangapur Road, Indira Nagar, Cidco areas. NMC building rules & contractor guide.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Kajaria', 'Dr. Fixit'],
    climateType: 'Semi-arid, warm summers, cool monsoon season, mild winters',
    soilType: 'Basalt rock in many areas, alluvial along Godavari river',
    localTips: [
      'Nashik is 3-4 hours from Mumbai — many contractors from Mumbai market operate here at lower rates',
      'Wine country climate means lower humidity than Mumbai — less waterproofing intensity needed',
      'Basalt rocky sub-soil in hills area — foundation excavation needs blasting budget (₹1.5-3L)',
      'NMC approval has improved recently — typically 45-60 days for standard residential plots',
    ],
    neighborhoods: ['Gangapur Road', 'Indira Nagar', 'Cidco', 'Dwarka', 'Panchvati', 'Satpur'],
  },
  {
    slug: 'vadodara',
    name: 'Vadodara',
    state: 'Gujarat',
    region: 'west',
    tier: 2,
    population: '2.1M+',
    constructionCost: { basic: 1300, standard: 1800, premium: 2800 },
    laborCostPerDay: { mason: 700, helper: 480, painter: 660 },
    steelRatePerKg: 68,
    cementBagRate: 380,
    metaTitle: 'Construction Cost & Home Renovation Answers for Vadodara | Biddaro',
    metaDescription: 'Vadodara construction costs 2024: ₹1,300-2,800/sqft. Expert answers for Alkapuri, Gotri, Waghodia Road areas. VMC building rules & contractor guide.',
    localBrands: ['UltraTech', 'Nuvoco', 'Asian Paints', 'Nitco Tiles', 'Polycab'],
    climateType: 'Semi-arid, hot summers (43°C), moderate monsoon',
    soilType: 'Alluvial and black cotton soil mix, moderate bearing capacity',
    localTips: [
      'VMC (Vadodara Municipal Corporation) building approval is digital and efficient — 30-45 days typical',
      'Cultural capital of Gujarat — high demand for traditional architectural elements in modern homes',
      'Extreme summer heat means white roof paint + thermal insulation is cost-effective investment',
      'Black cotton soil areas need deeper foundation — ask contractor to confirm soil type at your plot',
    ],
    neighborhoods: ['Alkapuri', 'Gotri', 'Waghodia Road', 'Subhanpura', 'Fatehgunj', 'Makarpura'],
  },
  {
    slug: 'patna',
    name: 'Patna',
    state: 'Bihar',
    region: 'east',
    tier: 2,
    population: '2.5M+',
    constructionCost: { basic: 1200, standard: 1700, premium: 2600 },
    laborCostPerDay: { mason: 650, helper: 440, painter: 610 },
    steelRatePerKg: 67,
    cementBagRate: 372,
    metaTitle: 'Construction Cost & Home Renovation Answers for Patna | Biddaro',
    metaDescription: 'Patna construction costs 2024: ₹1,200-2,600/sqft. Expert answers for Boring Road, Patliputra, Bailey Road areas. PMC building rules & contractor guide.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Kajaria', 'Polycab'],
    climateType: 'Humid subtropical, hot humid summers, very cold winters, heavy monsoon',
    soilType: 'Alluvial Gangetic flood plain, very soft silty soil, high water table',
    localTips: [
      'Patna\'s Gangetic alluvial soil is soft — raft foundation strongly recommended for any construction over G+1',
      'High water table in most areas — waterproof basement up to 1.5m above ground level',
      'Bihar has lower construction costs than national average — good time for investment construction',
      'PMC (Patna Municipal Corporation) approval process is improving — allow 60-90 days currently',
    ],
    neighborhoods: ['Boring Road', 'Patliputra Colony', 'Bailey Road', 'Kankarbagh', 'Rajendra Nagar', 'Saguna More'],
  },
  {
    slug: 'bhubaneswar',
    name: 'Bhubaneswar',
    state: 'Odisha',
    region: 'east',
    tier: 2,
    population: '1.0M+',
    constructionCost: { basic: 1300, standard: 1800, premium: 2800 },
    laborCostPerDay: { mason: 680, helper: 460, painter: 640 },
    steelRatePerKg: 68,
    cementBagRate: 378,
    metaTitle: 'Construction Cost & Home Renovation Answers for Bhubaneswar | Biddaro',
    metaDescription: 'Bhubaneswar construction costs 2024: ₹1,300-2,800/sqft. Expert answers for Patia, Nayapalli, Khandagiri areas. BDA building rules & contractor guide.',
    localBrands: ['Dalmia Cement', 'UltraTech', 'Asian Paints', 'Somany Tiles', 'Finolex'],
    climateType: 'Tropical wet, hot humid, heavy monsoon, occasional cyclones',
    soilType: 'Laterite in old city, alluvial in new areas, moderate bearing capacity',
    localTips: [
      'Cyclone-prone zone (Cyclone Fani 2019 caused massive damage) — use hurricane-resistant roof fastening',
      'BDA (Bhubaneswar Development Authority) is one of the better-run authorities in East India',
      'Smart city investment is driving up contractor demand — book early for quality tradespeople',
      'Good quality laterite stone locally available — use for compound walls and low-cost buildings',
    ],
    neighborhoods: ['Patia', 'Nayapalli', 'Khandagiri', 'Chandrasekharpur', 'Saheed Nagar', 'Unit-9'],
  },
  {
    slug: 'thiruvananthapuram',
    name: 'Thiruvananthapuram',
    state: 'Kerala',
    region: 'south',
    tier: 2,
    population: '1.7M+',
    constructionCost: { basic: 1600, standard: 2300, premium: 3700 },
    laborCostPerDay: { mason: 880, helper: 600, painter: 840 },
    steelRatePerKg: 71,
    cementBagRate: 396,
    metaTitle: 'Construction Cost & Home Renovation Answers for Thiruvananthapuram | Biddaro',
    metaDescription: 'Thiruvananthapuram construction costs 2024: ₹1,600-3,700/sqft. Expert answers for Kowdiar, Pattom, Kesavadasapuram areas. Kerala building tips.',
    localBrands: ['Malabar Cements', 'Ramco', 'Asian Paints', 'Somany Tiles', 'Polycab'],
    climateType: 'Tropical, two monsoons, high humidity year-round, 2,000mm+ annual rain',
    soilType: 'Laterite rock in most areas, sandy coastal strip',
    localTips: [
      'Kerala\'s coastal state — entire waterproofing budget must be maximized; include anti-carbonation coating',
      'Highly skilled traditional masons for Kerala traditional homes (Tharavadu/Nalukettu) are available',
      'LSGD (Local Self Government) approval in Thiruvananthapuram is faster than bigger metros',
      'Double monsoon means roof drainage design is critical — ensure proper slope (minimum 1:50) for all roofs',
    ],
    neighborhoods: ['Kowdiar', 'Pattom', 'Kesavadasapuram', 'Sreekaryam', 'Kazhakuttom', 'Vattiyoorkavu'],
  },
  {
    slug: 'mangalore',
    name: 'Mangalore',
    state: 'Karnataka',
    region: 'south',
    tier: 3,
    population: '0.8M+',
    constructionCost: { basic: 1500, standard: 2100, premium: 3300 },
    laborCostPerDay: { mason: 800, helper: 540, painter: 760 },
    steelRatePerKg: 71,
    cementBagRate: 392,
    metaTitle: 'Construction Cost & Home Renovation Answers for Mangalore | Biddaro',
    metaDescription: 'Mangalore construction costs 2024: ₹1,500-3,300/sqft. Expert answers for Kadri, Bejai, Pandeshwar areas. Coastal construction & monsoon tips.',
    localBrands: ['Ramco Cement', 'UltraTech', 'Asian Paints', 'Kajaria', 'Dr. Fixit'],
    climateType: 'Tropical monsoon, very heavy rainfall (3,500mm+), high humidity',
    soilType: 'Laterite rock in hills, alluvial near river, coastal sandy areas',
    localTips: [
      'Mangalore gets India\'s heaviest monsoon outside Northeast — waterproofing budget must be maximum (₹150-200/sqft)',
      'Traditional Mangalorean tile roof homes have excellent rain-shedding — consider hybrid modern-traditional design',
      'MCC (Mangalore City Corporation) approval takes 30-45 days for standard residential',
      'High NRI population with Gulf remittances — premium construction quality is the norm',
    ],
    neighborhoods: ['Kadri', 'Bejai', 'Pandeshwar', 'Attavar', 'Kankanady', 'Balmatta'],
  },
  {
    slug: 'amritsar',
    name: 'Amritsar',
    state: 'Punjab',
    region: 'north',
    tier: 3,
    population: '1.2M+',
    constructionCost: { basic: 1300, standard: 1800, premium: 2900 },
    laborCostPerDay: { mason: 700, helper: 480, painter: 660 },
    steelRatePerKg: 69,
    cementBagRate: 382,
    metaTitle: 'Construction Cost & Home Renovation Answers for Amritsar | Biddaro',
    metaDescription: 'Amritsar construction costs 2024: ₹1,300-2,900/sqft. Expert answers for Ranjit Avenue, Civil Lines, GT Road areas. Punjab NRI home tips.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Kajaria', 'Polycab'],
    climateType: 'Semi-arid, extreme heat (46°C) in summer, very cold foggy winters',
    soilType: 'Alluvial Punjab plains, excellent bearing capacity',
    localTips: [
      'High NRI population — premium construction quality and finishes are expected standard',
      'Very cold foggy winters require double-glazed windows and insulated walls — budget ₹2-3L extra',
      'AMDA (Amritsar Metropolitan Development Authority) approval required for new construction',
      'Religious tourism drives robust construction market — good contractor availability and competition',
    ],
    neighborhoods: ['Ranjit Avenue', 'Civil Lines', 'GT Road', 'Lawrence Road', 'Batala Road', 'Majitha Road'],
  },
  {
    slug: 'agra',
    name: 'Agra',
    state: 'Uttar Pradesh',
    region: 'north',
    tier: 3,
    population: '1.8M+',
    constructionCost: { basic: 1200, standard: 1700, premium: 2700 },
    laborCostPerDay: { mason: 660, helper: 450, painter: 620 },
    steelRatePerKg: 67,
    cementBagRate: 374,
    metaTitle: 'Construction Cost & Home Renovation Answers for Agra | Biddaro',
    metaDescription: 'Agra construction costs 2024: ₹1,200-2,700/sqft. Expert answers for Kamla Nagar, Sikandra, Shahganj areas. UP RERA building tips for Agra.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Somany Tiles', 'Finolex'],
    climateType: 'Semi-arid, very hot summer (46°C), cold winters, moderate monsoon',
    soilType: 'Alluvial with some rocky patches near Yamuna, generally good bearing capacity',
    localTips: [
      'Heritage zone near Taj Mahal has strict height restrictions — verify your plot\'s heritage buffer zone status',
      'Agra Development Authority (ADA) approval is required — allow 45-60 days',
      'Extreme summer requires good cross-ventilation design or additional insulation investment',
      'Affordable construction market — good quality work at lower cost than Delhi NCR',
    ],
    neighborhoods: ['Kamla Nagar', 'Sikandra', 'Shahganj', 'Dayalbagh', 'Tajganj', 'Bodla'],
  },
  {
    slug: 'dehradun',
    name: 'Dehradun',
    state: 'Uttarakhand',
    region: 'north',
    tier: 3,
    population: '0.8M+',
    constructionCost: { basic: 1400, standard: 1900, premium: 3100 },
    laborCostPerDay: { mason: 720, helper: 490, painter: 680 },
    steelRatePerKg: 69,
    cementBagRate: 385,
    metaTitle: 'Construction Cost & Home Renovation Answers for Dehradun | Biddaro',
    metaDescription: 'Dehradun construction costs 2024: ₹1,400-3,100/sqft. Expert answers for Rajpur Road, ISBT, Patel Nagar areas. Hill construction & landslide tips.',
    localBrands: ['UltraTech', 'ACC', 'Asian Paints', 'Johnson Tiles', 'Polycab'],
    climateType: 'Subtropical highland, pleasant year-round, heavy monsoon rains, cold winters',
    soilType: 'Rocky hillside terrain, alluvial Doon valley floor, some landslide-prone zones',
    localTips: [
      'Hilly terrain requires slope stability analysis before building — landslide risk assessment is mandatory',
      'MDDA (Mussoorie Dehradun Development Authority) approval required — takes 45-90 days',
      'Heavy monsoon in hills (2,000mm+) — excellent waterproofing and slope drainage are critical',
      'Seismic Zone IV — earthquake-resistant construction with shear walls is essential',
    ],
    neighborhoods: ['Rajpur Road', 'ISBT Corridor', 'Patel Nagar', 'Dalanwala', 'Raipur', 'Clement Town'],
  },
];

export function getCity(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((c) => c.slug);
}

export function getCitiesByRegion(region: CityData['region']): CityData[] {
  return CITIES.filter((c) => c.region === region);
}

export function getCitiesByTier(tier: 1 | 2 | 3): CityData[] {
  return CITIES.filter((c) => c.tier === tier);
}
