export interface UAECityData {
  slug: string;
  name: string;
  emirate: string;
  region: 'capital' | 'northern' | 'eastern' | 'western';
  tier: 1 | 2 | 3;
  population: string;
  constructionCost: { basic: number; standard: number; premium: number }; // AED per sqft
  laborCostPerDay: { mason: number; helper: number; painter: number }; // AED
  steelRatePerKg: number; // AED
  cementBagRate: number; // AED
  metaTitle: string;
  metaDescription: string;
  localBrands: string[];
  climateType: string;
  soilType: string;
  localTips: string[];
  neighborhoods: string[];
  nearbyCity?: string;
}

export const UAE_CITIES: UAECityData[] = [
  {
    slug: 'dubai-city',
    name: 'Dubai',
    emirate: 'Dubai',
    region: 'western',
    tier: 1,
    population: '3,500,000+',
    constructionCost: { basic: 900, standard: 1500, premium: 2800 },
    laborCostPerDay: { mason: 220, helper: 120, painter: 200 },
    steelRatePerKg: 5.5,
    cementBagRate: 22,
    metaTitle: 'Construction Cost & Renovation Answers for Dubai | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Dubai. Rates from AED 900–2,800/sqft across Deira, Bur Dubai, Al Quoz & more. Compare material prices and find trusted contractors.',
    localBrands: ['RAK Ceramics', 'Danube Home', 'National Paints', 'Dragon Mart', 'Al Futtaim'],
    climateType: 'Hot desert / coastal humid',
    soilType: 'Sandy with coastal saline patches',
    localTips: [
      'All construction must comply with Dubai Municipality (DM) building codes and obtain NOC clearances before starting work.',
      'Use heat-reflective exterior coatings and high-SRI materials to meet Al Safat green building requirements and reduce cooling loads.',
      'Plan major concreting and outdoor structural work during cooler months (November–March) to avoid extreme summer temperatures exceeding 48°C.',
      'Ensure all electrical and plumbing installations meet DEWA (Dubai Electricity and Water Authority) standards for final utility connections.',
    ],
    neighborhoods: ['Deira', 'Bur Dubai', 'Al Quoz', 'Al Karama', 'Satwa', 'Oud Metha', 'Al Rashidiya'],
    nearbyCity: 'sharjah-city',
  },
  {
    slug: 'abu-dhabi-city',
    name: 'Abu Dhabi',
    emirate: 'Abu Dhabi',
    region: 'capital',
    tier: 1,
    population: '1,500,000+',
    constructionCost: { basic: 850, standard: 1400, premium: 2600 },
    laborCostPerDay: { mason: 210, helper: 115, painter: 190 },
    steelRatePerKg: 5.3,
    cementBagRate: 21,
    metaTitle: 'Construction Cost & Renovation Answers for Abu Dhabi | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Abu Dhabi. Rates from AED 850–2,600/sqft across Al Khalidiyah, Tourist Club, Mushrif & more. Compare material prices and find contractors.',
    localBrands: ['RAK Ceramics', 'National Paints', 'Hempel', 'Al Jazeera Paints', 'Danube Home'],
    climateType: 'Hot desert / coastal humid',
    soilType: 'Sandy with sabkha (salt flat) deposits',
    localTips: [
      'All projects must meet Estidama Pearl Rating System requirements for sustainability — minimum 1 Pearl for villas, 2 Pearls for government buildings.',
      'Sabkha soil conditions require deep pile foundations and sulphate-resistant cement to prevent structural damage from salt intrusion.',
      'Coordinate with Abu Dhabi Distribution Company (ADDC) early for water and electricity connections — lead times can be 4–6 weeks.',
      'Use insulated concrete forms (ICF) or cavity walls with thermal insulation to combat summer temperatures regularly exceeding 45°C.',
    ],
    neighborhoods: ['Al Khalidiyah', 'Tourist Club Area', 'Mushrif', 'Al Bateen', 'Khalifa City A', 'Al Nahyan', 'Al Reef'],
    nearbyCity: 'khalifa-city',
  },
  {
    slug: 'sharjah-city',
    name: 'Sharjah',
    emirate: 'Sharjah',
    region: 'northern',
    tier: 1,
    population: '1,400,000+',
    constructionCost: { basic: 700, standard: 1100, premium: 2000 },
    laborCostPerDay: { mason: 180, helper: 100, painter: 160 },
    steelRatePerKg: 5.0,
    cementBagRate: 20,
    metaTitle: 'Construction Cost & Renovation Answers for Sharjah | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Sharjah. Rates from AED 700–2,000/sqft across Al Nahda, Al Majaz, Al Khan & more. Compare material prices and find contractors.',
    localBrands: ['RAK Ceramics', 'National Paints', 'Danube Home', 'Al Jazeera Paints', 'Hempel'],
    climateType: 'Hot desert / coastal humid',
    soilType: 'Sandy with coastal sediment layers',
    localTips: [
      'Sharjah Municipality requires strict approval for building plans — ensure architectural drawings are stamped by an approved consultant before submission.',
      'Sandstorm-proof exterior finishes and sealed window frames are essential; Sharjah experiences frequent shamal winds from June to August.',
      'Use corrosion-resistant reinforcement (epoxy-coated rebar) for structures near the coast to counter salt-laden humidity.',
      'Plan logistics carefully — heavy vehicle movement restrictions during peak hours affect material delivery schedules across Sharjah.',
    ],
    neighborhoods: ['Al Nahda', 'Al Majaz', 'Al Khan', 'Al Qasimia', 'Muwaileh', 'Al Taawun', 'University City'],
    nearbyCity: 'dubai-city',
  },
  {
    slug: 'al-ain',
    name: 'Al Ain',
    emirate: 'Abu Dhabi',
    region: 'eastern',
    tier: 2,
    population: '750,000+',
    constructionCost: { basic: 650, standard: 1000, premium: 1800 },
    laborCostPerDay: { mason: 175, helper: 95, painter: 155 },
    steelRatePerKg: 5.2,
    cementBagRate: 21,
    metaTitle: 'Construction Cost & Renovation Answers for Al Ain | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Al Ain. Rates from AED 650–1,800/sqft across Jimi, Muwaiji, Zakher & more. Compare material prices and find contractors.',
    localBrands: ['RAK Ceramics', 'National Paints', 'Hempel', 'Danube Home', 'Al Jazeera Paints'],
    climateType: 'Hot desert / inland arid',
    soilType: 'Rocky with gravel and compacted sand',
    localTips: [
      'Al Ain sits at the base of Jebel Hafeet — rocky subsoil may require blasting or heavy excavation for foundations, increasing costs by 10–15%.',
      'Estidama Pearl Rating applies across the Abu Dhabi emirate; all Al Ain projects must comply with sustainability benchmarks.',
      'Inland temperatures regularly exceed 50°C in summer — schedule all concreting for early morning or night shifts to prevent rapid moisture loss.',
      'Coordinate with Al Ain Distribution Company (AADC) for utility connections; water supply infrastructure is more limited than in coastal cities.',
    ],
    neighborhoods: ['Jimi', 'Muwaiji', 'Zakher', 'Al Mutawaa', 'Al Khabisi', 'Hili'],
    nearbyCity: 'abu-dhabi-city',
  },
  {
    slug: 'ajman-city',
    name: 'Ajman',
    emirate: 'Ajman',
    region: 'northern',
    tier: 2,
    population: '500,000+',
    constructionCost: { basic: 600, standard: 950, premium: 1700 },
    laborCostPerDay: { mason: 165, helper: 90, painter: 145 },
    steelRatePerKg: 4.8,
    cementBagRate: 19,
    metaTitle: 'Construction Cost & Renovation Answers for Ajman | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Ajman. Rates from AED 600–1,700/sqft across Al Nuaimiya, Rashidiya, Al Jurf & more. Compare material prices and find contractors.',
    localBrands: ['RAK Ceramics', 'National Paints', 'Dragon Mart', 'Danube Home', 'Al Jazeera Paints'],
    climateType: 'Hot desert / coastal humid',
    soilType: 'Sandy with high water table near coast',
    localTips: [
      'Ajman Municipality offers faster permit processing than larger emirates — typical turnaround is 2–3 weeks for residential projects.',
      'High water table near the coast requires dewatering during excavation and waterproof membranes for basements and ground floors.',
      'Source materials from nearby Sharjah industrial areas (Al Jurf, SAIF Zone) to reduce transport costs significantly.',
      'Use anti-humidity treatments on all interior walls — coastal Ajman sees 85%+ humidity levels for much of the year.',
    ],
    neighborhoods: ['Al Nuaimiya', 'Rashidiya', 'Al Jurf', 'Al Hamidiya', 'Mushairef', 'Emirates City'],
    nearbyCity: 'sharjah-city',
  },
  {
    slug: 'rak-city',
    name: 'Ras Al Khaimah',
    emirate: 'Ras Al Khaimah',
    region: 'northern',
    tier: 2,
    population: '350,000+',
    constructionCost: { basic: 600, standard: 900, premium: 1650 },
    laborCostPerDay: { mason: 160, helper: 88, painter: 140 },
    steelRatePerKg: 4.7,
    cementBagRate: 19,
    metaTitle: 'Construction Cost & Renovation Answers for Ras Al Khaimah | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Ras Al Khaimah. Rates from AED 600–1,650/sqft across Al Nakheel, Dafan Al Khor, Khuzam & more. Compare material prices and find contractors.',
    localBrands: ['RAK Ceramics', 'Stevin Rock', 'National Paints', 'Julphar Paints', 'Danube Home'],
    climateType: 'Hot desert / semi-arid mountainous',
    soilType: 'Rocky mountain base with alluvial sand deposits',
    localTips: [
      'RAK has local quarries and RAK Ceramics factory — source aggregates, tiles, and ceramic products locally for 15–20% cost savings.',
      'Mountain-adjacent sites in Jebel Jais foothills may have rocky subsoil requiring specialized foundation engineering.',
      'RAK Municipality building codes are evolving; verify latest requirements before submitting plans as regulations update frequently.',
      'Wadi flooding is a risk in mountainous areas — ensure proper drainage design and avoid building in natural water channels.',
    ],
    neighborhoods: ['Al Nakheel', 'Dafan Al Khor', 'Khuzam', 'Al Hamra Village', 'Mina Al Arab', 'Julphar Towers'],
    nearbyCity: 'uaq-city',
  },
  {
    slug: 'fujairah-city',
    name: 'Fujairah',
    emirate: 'Fujairah',
    region: 'eastern',
    tier: 2,
    population: '250,000+',
    constructionCost: { basic: 580, standard: 880, premium: 1600 },
    laborCostPerDay: { mason: 155, helper: 85, painter: 138 },
    steelRatePerKg: 4.9,
    cementBagRate: 20,
    metaTitle: 'Construction Cost & Renovation Answers for Fujairah | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Fujairah. Rates from AED 580–1,600/sqft across Al Faseel, Rugaylat, Merashid & more. Compare material prices and find contractors.',
    localBrands: ['RAK Ceramics', 'Fujairah Cement', 'National Paints', 'Hempel', 'Danube Home'],
    climateType: 'Hot humid coastal / mountainous',
    soilType: 'Rocky (Hajar Mountains) with coastal coral and sand',
    localTips: [
      'Fujairah Cement Industries operates locally — procure cement directly from the factory for competitive rates and reduced transport costs.',
      'Eastern coast exposure to the Gulf of Oman means higher humidity and salt spray; specify marine-grade steel and coatings for all coastal projects.',
      'Rocky terrain in the Hajar Mountain foothills often requires rock-breaking or blasting, adding 10–20% to foundation costs.',
      'Fujairah is seismically more active than the western UAE — follow updated seismic design codes for structural safety.',
    ],
    neighborhoods: ['Al Faseel', 'Rugaylat', 'Merashid', 'Sakamkam', 'Al Hayl', 'Dibba Al Fujairah'],
    nearbyCity: 'rak-city',
  },
  {
    slug: 'uaq-city',
    name: 'Umm Al Quwain',
    emirate: 'Umm Al Quwain',
    region: 'northern',
    tier: 3,
    population: '80,000+',
    constructionCost: { basic: 550, standard: 850, premium: 1500 },
    laborCostPerDay: { mason: 150, helper: 80, painter: 130 },
    steelRatePerKg: 4.6,
    cementBagRate: 18,
    metaTitle: 'Construction Cost & Renovation Answers for Umm Al Quwain | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Umm Al Quwain. Rates from AED 550–1,500/sqft across Old Town, Al Salamah, Al Raas & more. Compare material prices and find contractors.',
    localBrands: ['RAK Ceramics', 'National Paints', 'Dragon Mart', 'Al Jazeera Paints', 'Danube Home'],
    climateType: 'Hot desert / coastal',
    soilType: 'Sandy with sabkha patches near lagoons',
    localTips: [
      'UAQ offers the lowest land and construction costs in the UAE — ideal for budget-conscious villa and warehouse projects.',
      'Sabkha (salt flat) soil near the coastal lagoons requires soil treatment and sulphate-resistant concrete for foundations.',
      'Smaller contractor pool means planning ahead is crucial; book skilled trades 4–6 weeks in advance to avoid delays.',
      'Source most building materials from nearby Ajman and RAK industrial zones for better availability and competitive pricing.',
    ],
    neighborhoods: ['Old Town', 'Al Salamah', 'Al Raas', 'Al Aahad', 'Falaj Al Mualla'],
    nearbyCity: 'ajman-city',
  },
  {
    slug: 'khalifa-city',
    name: 'Khalifa City',
    emirate: 'Abu Dhabi',
    region: 'capital',
    tier: 2,
    population: '120,000+',
    constructionCost: { basic: 800, standard: 1300, premium: 2400 },
    laborCostPerDay: { mason: 200, helper: 110, painter: 180 },
    steelRatePerKg: 5.3,
    cementBagRate: 22,
    metaTitle: 'Construction Cost & Renovation Answers for Khalifa City | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Khalifa City, Abu Dhabi. Rates from AED 800–2,400/sqft. Premium villa community near Abu Dhabi International Airport.',
    localBrands: ['RAK Ceramics', 'Hempel', 'National Paints', 'Al Futtaim', 'Danube Home'],
    climateType: 'Hot desert / inland arid',
    soilType: 'Compacted desert sand with dune formations',
    localTips: [
      'Khalifa City falls under Abu Dhabi Municipality jurisdiction — Estidama Pearl Rating compliance is mandatory for all new construction.',
      'Proximity to Abu Dhabi International Airport means height restrictions apply; verify with the General Civil Aviation Authority before finalizing designs.',
      'Underground utility infrastructure is well-established — coordinate with ADDC and ADNOC Distribution for seamless service connections.',
      'Compacted sand subsoil is generally favorable for shallow foundations but conduct geotechnical surveys to confirm bearing capacity.',
    ],
    neighborhoods: ['Khalifa City A', 'Khalifa City B', 'Al Forsan Village', 'Al Reef Villas', 'Al Rayyana'],
    nearbyCity: 'abu-dhabi-city',
  },
  {
    slug: 'jebel-ali',
    name: 'Jebel Ali',
    emirate: 'Dubai',
    region: 'western',
    tier: 2,
    population: '150,000+',
    constructionCost: { basic: 750, standard: 1200, premium: 2200 },
    laborCostPerDay: { mason: 190, helper: 105, painter: 170 },
    steelRatePerKg: 5.0,
    cementBagRate: 21,
    metaTitle: 'Construction Cost & Renovation Answers for Jebel Ali | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Jebel Ali, Dubai. Rates from AED 750–2,200/sqft. Industrial and residential hub near Jebel Ali Port and Expo City.',
    localBrands: ['RAK Ceramics', 'Danube Home', 'Dragon Mart', 'National Paints', 'Al Futtaim'],
    climateType: 'Hot desert / coastal',
    soilType: 'Sandy with reclaimed land sections',
    localTips: [
      'Jebel Ali Free Zone (JAFZA) has separate building regulations for commercial/industrial projects — verify jurisdiction before applying for permits.',
      'Proximity to Jebel Ali Port means easy access to imported construction materials at competitive rates; buy direct from port-side suppliers.',
      'Reclaimed land areas may have variable soil compaction — always conduct thorough geotechnical investigations before foundation design.',
      'DEWA connections are well-serviced in this area; coordinate early for high-capacity industrial power requirements.',
    ],
    neighborhoods: ['Jebel Ali Village', 'Jebel Ali Industrial', 'Discovery Gardens', 'Gardens', 'The Gardens', 'Jebel Ali Hills'],
    nearbyCity: 'dubai-city',
  },
  {
    slug: 'dubai-marina',
    name: 'Dubai Marina',
    emirate: 'Dubai',
    region: 'western',
    tier: 1,
    population: '60,000+',
    constructionCost: { basic: 1100, standard: 1800, premium: 3500 },
    laborCostPerDay: { mason: 250, helper: 130, painter: 220 },
    steelRatePerKg: 5.8,
    cementBagRate: 24,
    metaTitle: 'Construction Cost & Renovation Answers for Dubai Marina | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Dubai Marina. Rates from AED 1,100–3,500/sqft. Premium waterfront district with luxury high-rise towers and marina living.',
    localBrands: ['RAK Ceramics', 'Porcelanosa', 'Hempel', 'Danube Home', 'Al Futtaim'],
    climateType: 'Hot coastal humid',
    soilType: 'Reclaimed sandy seabed with marine sediment',
    localTips: [
      'Most renovation work in Dubai Marina towers requires RERA-approved contractors and owner association (OA) approval before any structural changes.',
      'High-rise logistics add 15–25% to renovation costs due to material hoisting, parking restrictions, and elevator scheduling for deliveries.',
      'Salt-laden coastal air accelerates corrosion — use marine-grade finishes, stainless steel fixtures, and anti-corrosion coatings on all exposed metalwork.',
      'Noise and work-hour restrictions are strictly enforced by building management; typically work is permitted only 9 AM–6 PM on weekdays.',
    ],
    neighborhoods: ['Marina Walk', 'Marina Promenade', 'Jumeirah Beach Residence', 'The Walk', 'Bluewaters Island'],
    nearbyCity: 'jebel-ali',
  },
  {
    slug: 'jumeirah',
    name: 'Jumeirah',
    emirate: 'Dubai',
    region: 'western',
    tier: 1,
    population: '45,000+',
    constructionCost: { basic: 1000, standard: 1700, premium: 3200 },
    laborCostPerDay: { mason: 240, helper: 125, painter: 210 },
    steelRatePerKg: 5.7,
    cementBagRate: 24,
    metaTitle: 'Construction Cost & Renovation Answers for Jumeirah | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Jumeirah, Dubai. Rates from AED 1,000–3,200/sqft. Prestigious beachfront villa district with luxury homes and renovations.',
    localBrands: ['RAK Ceramics', 'Porcelanosa', 'National Paints', 'Hempel', 'Al Futtaim'],
    climateType: 'Hot coastal humid',
    soilType: 'Sandy coastal with coral limestone substrate',
    localTips: [
      'Jumeirah is a heritage-sensitive area — Dubai Municipality may impose design guidelines to maintain the neighborhood character of established villa communities.',
      'Beachfront proximity means aggressive salt corrosion; budget for premium anti-corrosion treatments on all structural steel and external fixtures.',
      'Many Jumeirah villas are 20–30 years old — renovation projects should include full electrical rewiring and plumbing replacement to meet current DM codes.',
      'Premium landscaping with irrigation is standard for Jumeirah villas; factor in DEWA grey-water recycling systems to reduce water costs.',
    ],
    neighborhoods: ['Jumeirah 1', 'Jumeirah 2', 'Jumeirah 3', 'Umm Suqeim', 'Al Safa', 'Madinat Jumeirah'],
    nearbyCity: 'dubai-city',
  },
  {
    slug: 'business-bay',
    name: 'Business Bay',
    emirate: 'Dubai',
    region: 'western',
    tier: 1,
    population: '55,000+',
    constructionCost: { basic: 950, standard: 1600, premium: 3000 },
    laborCostPerDay: { mason: 235, helper: 122, painter: 205 },
    steelRatePerKg: 5.6,
    cementBagRate: 23,
    metaTitle: 'Construction Cost & Renovation Answers for Business Bay | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Business Bay, Dubai. Rates from AED 950–3,000/sqft. Central business and residential district along the Dubai Canal.',
    localBrands: ['RAK Ceramics', 'Danube Home', 'Hempel', 'National Paints', 'Al Futtaim'],
    climateType: 'Hot desert / urban heat island',
    soilType: 'Reclaimed canal-side sandy soil',
    localTips: [
      'Business Bay buildings are managed by individual OAs with varying fit-out guidelines — obtain the building fit-out manual before starting any renovation.',
      'Dubai Canal proximity creates localized humidity; waterproofing lower floors and using dehumidification systems is strongly recommended.',
      'Parking and loading dock access is limited in most Business Bay towers — coordinate material deliveries during off-peak hours (before 7 AM or after 9 PM).',
      'All commercial fit-outs must obtain DCD (Dubai Civil Defence) approval for fire safety compliance before occupancy.',
    ],
    neighborhoods: ['Executive Towers', 'Bay Square', 'Marasi Drive', 'The Opus', 'Ubora Towers', 'Aspect Tower'],
    nearbyCity: 'dubai-city',
  },
  {
    slug: 'al-barsha',
    name: 'Al Barsha',
    emirate: 'Dubai',
    region: 'western',
    tier: 2,
    population: '85,000+',
    constructionCost: { basic: 800, standard: 1300, premium: 2400 },
    laborCostPerDay: { mason: 195, helper: 108, painter: 175 },
    steelRatePerKg: 5.2,
    cementBagRate: 22,
    metaTitle: 'Construction Cost & Renovation Answers for Al Barsha | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Al Barsha, Dubai. Rates from AED 800–2,400/sqft. Family-friendly residential district near Mall of the Emirates.',
    localBrands: ['RAK Ceramics', 'National Paints', 'Danube Home', 'Dragon Mart', 'Al Jazeera Paints'],
    climateType: 'Hot desert / inland urban',
    soilType: 'Compacted desert sand with gypsum layers',
    localTips: [
      'Al Barsha has a mix of older villas and newer developments — older properties may need full structural assessments before major renovation work.',
      'Gypsum-rich soil layers can cause differential settlement; conduct soil testing and design foundations accordingly to prevent cracking.',
      'Good road connectivity and proximity to Al Quoz Industrial Area means lower material transport costs compared to more remote Dubai neighborhoods.',
      'DEWA smart meter installations are standard for new connections; plan electrical layouts to accommodate smart home integration.',
    ],
    neighborhoods: ['Al Barsha 1', 'Al Barsha 2', 'Al Barsha 3', 'Al Barsha South', 'Arjan', 'Al Quoz'],
    nearbyCity: 'dubai-city',
  },
  {
    slug: 'mussafah',
    name: 'Mussafah',
    emirate: 'Abu Dhabi',
    region: 'capital',
    tier: 2,
    population: '200,000+',
    constructionCost: { basic: 650, standard: 1000, premium: 1800 },
    laborCostPerDay: { mason: 170, helper: 92, painter: 150 },
    steelRatePerKg: 4.9,
    cementBagRate: 20,
    metaTitle: 'Construction Cost & Renovation Answers for Mussafah | Biddaro',
    metaDescription:
      'Get accurate construction and renovation cost estimates for Mussafah, Abu Dhabi. Rates from AED 650–1,800/sqft. Major industrial and residential district with affordable construction options.',
    localBrands: ['RAK Ceramics', 'National Paints', 'Hempel', 'Al Jazeera Paints', 'Danube Home'],
    climateType: 'Hot desert / industrial urban',
    soilType: 'Sandy with sabkha and high water table areas',
    localTips: [
      'Mussafah Industrial Area (ICAD) has dedicated zones for construction material suppliers — source steel, cement, and aggregates locally at wholesale rates.',
      'Sabkha soil with high water table is common; use sulphate-resistant cement and install proper ground-level waterproofing for all structures.',
      'Estidama Pearl Rating compliance is required; even industrial and warehouse projects must meet minimum sustainability benchmarks.',
      'Mussafah has the largest concentration of building material suppliers in Abu Dhabi — compare quotes from multiple vendors to get the best rates.',
    ],
    neighborhoods: ['Mussafah Industrial', 'Shabiya', 'ICAD', 'Mussafah Residential', 'Mussafah Bridge', 'South Mussafah'],
    nearbyCity: 'abu-dhabi-city',
  },
];

export function getUAECityBySlug(slug: string): UAECityData | undefined {
  return UAE_CITIES.find((c) => c.slug === slug);
}
