// ─── Loan Glossary Data ───────────────────────────────────────────────────────
// 50 financial terms with definitions, examples, and FAQs

export interface GlossaryFaq {
  q: string;
  a: string;
}

export interface GlossaryTerm {
  slug: string;
  term: string;
  shortDef: string;          // 1-sentence definition for meta/cards
  metaTitle: string;
  metaDescription: string;
  definition: string;        // 3–5 sentence full definition
  example: string;           // Concrete numerical example
  relatedLoanLink: string;
  relatedLoanName: string;
  relatedTerms: string[];    // slugs
  faqs: GlossaryFaq[];
  tags: string[];
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    slug: 'emi',
    term: 'EMI',
    shortDef: 'Equated Monthly Instalment — the fixed monthly payment made to repay a loan.',
    metaTitle: 'What is EMI? Equated Monthly Instalment Explained | Biddaro',
    metaDescription: 'EMI meaning in loans — definition, formula, how it works, examples for home loan, personal loan, construction loan. Calculate your EMI free.',
    definition: 'EMI (Equated Monthly Instalment) is a fixed amount paid by a borrower to a lender on a specified date each calendar month. EMIs are used to pay off both interest and principal each month so that the loan is fully repaid over the agreed tenure. In the early months, a larger portion of the EMI goes toward interest; as the loan matures, more goes toward reducing the principal.',
    example: 'For a ₹10 Lakh home construction loan at 8.5% p.a. over 15 years, the EMI = ₹9,847/month. In month 1, ₹7,083 goes to interest and ₹2,764 to principal. By month 100, ₹3,942 goes to interest and ₹5,905 to principal.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['principal', 'interest-rate', 'tenure', 'moratorium', 'foreclosure'],
    tags: ['emi meaning', 'equated monthly instalment', 'emi formula india', 'loan emi calculator'],
    faqs: [
      { q: 'What does EMI stand for in loans?', a: 'EMI stands for Equated Monthly Instalment. It is the fixed monthly payment a borrower makes to the lender until the loan is fully repaid. Each EMI contains two components: interest on the outstanding principal and a portion of the principal itself. The formula is: EMI = P × r × (1+r)^n ÷ [(1+r)^n − 1], where P = principal, r = monthly rate, n = tenure in months.' },
      { q: 'How is EMI calculated in India?', a: 'EMI is calculated using the reducing balance method in India. The formula: EMI = [P × r × (1+r)^n] ÷ [(1+r)^n − 1]. Example: ₹5 Lakh personal loan at 14% p.a. for 5 years. Monthly rate r = 14/12/100 = 0.01167. n = 60 months. EMI = 5,00,000 × 0.01167 × (1.01167)^60 ÷ [(1.01167)^60 − 1] = ₹11,634/month.' },
      { q: 'What is the difference between EMI and monthly interest?', a: 'Monthly interest is only the interest component for that month (outstanding balance × monthly rate). EMI includes both the monthly interest and a principal repayment component. Monthly interest decreases each month (as principal reduces) while EMI stays fixed throughout the tenure — the difference (EMI minus monthly interest) goes toward principal repayment, which increases every month.' },
    ],
  },
  {
    slug: 'cibil-score',
    term: 'CIBIL Score',
    shortDef: 'A 3-digit credit score (300–900) that summarises your credit history for lenders.',
    metaTitle: 'What is CIBIL Score? Definition, Range, How It Works | Biddaro',
    metaDescription: 'CIBIL score meaning — what it is, range (300–900), how lenders use it, how to check free, and how to improve for better loan rates in India.',
    definition: 'CIBIL Score (also called credit score) is a 3-digit number ranging from 300 to 900, generated by TransUnion CIBIL (Credit Information Bureau India Limited) based on your credit history. It summarises your repayment track record, credit utilisation, number of active loans, and credit enquiries. Lenders in India use it as the primary indicator of creditworthiness when evaluating loan applications.',
    example: 'A CIBIL score of 780 typically gets you a home loan at 8.5–9% p.a., while a score of 670 may get 11–12% p.a. on the same ₹30 Lakh loan — a difference of ₹3,000–₹5,000/month in EMI.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['principal', 'interest-rate', 'dpd', 'co-applicant'],
    tags: ['cibil score meaning', 'credit score india', 'what is cibil', 'cibil score range'],
    faqs: [
      { q: 'What is a good CIBIL score for a loan in India?', a: 'A CIBIL score of 750 or above is considered excellent and qualifies you for the best loan rates. Scores of 700–749 are good and qualify for most loans at moderate rates. Scores of 650–699 are fair — you may qualify but at higher rates. Below 650 is poor — many lenders will reject the application. Check your CIBIL score free once a year at cibil.com.' },
      { q: 'How long does it take to build a good CIBIL score?', a: 'Building a CIBIL score from scratch takes 6–12 months after your first credit product (credit card or small loan). Improving a poor score (below 650) typically takes 6–12 months of consistent on-time payments, reduced credit card utilisation (below 30%), and no new credit applications. Disputing and correcting errors in your CIBIL report can show results within 30–60 days.' },
      { q: 'Does checking CIBIL score reduce it?', a: 'No — checking your own CIBIL score is a soft enquiry and does not reduce your score. Only when a lender checks your score (hard enquiry upon loan application) does it drop slightly by 5–10 points. Multiple loan applications within a short period cause multiple hard enquiries, which can significantly drop your score.' },
    ],
  },
  {
    slug: 'principal',
    term: 'Principal',
    shortDef: 'The original amount borrowed in a loan, excluding interest.',
    metaTitle: 'What is Principal in a Loan? Definition & Examples | Biddaro',
    metaDescription: 'Principal loan amount meaning — the original sum borrowed. How principal reduces with EMI payments, difference from interest. Explained with examples.',
    definition: 'Principal is the original amount of money borrowed from a lender, before any interest is added. In a loan, the total repayment = principal + interest. With each EMI payment, a portion goes toward reducing the outstanding principal (called principal repayment) and the rest covers the interest for that period. The outstanding principal decreases each month until it reaches zero at the end of the tenure.',
    example: 'You borrow ₹20 Lakh (principal) at 9% p.a. for 20 years. Monthly EMI = ₹17,995. In month 1: ₹15,000 goes to interest (₹20L × 0.75%) and ₹2,995 reduces the principal. By year 5, outstanding principal ≈ ₹17.7 Lakh.',
    relatedLoanLink: '/loans/personal',
    relatedLoanName: 'Personal Loan',
    relatedTerms: ['emi', 'interest-rate', 'tenure', 'ltv-ratio'],
    tags: ['principal loan meaning', 'principal amount definition', 'loan principal india'],
    faqs: [
      { q: 'What is the difference between principal and interest in a loan?', a: 'Principal is the actual amount borrowed. Interest is the fee paid for borrowing that money, calculated as a percentage of the outstanding principal. Your total loan cost = principal + total interest paid over the tenure. Example: ₹10 Lakh borrowed at 10% for 10 years — you repay ₹15.8 Lakh total. Principal = ₹10 Lakh, total interest = ₹5.8 Lakh.' },
      { q: 'How does principal reduce with each EMI?', a: 'In a reducing balance loan, each EMI first covers the interest for that month, then the remainder reduces the principal. Early EMIs are mostly interest (small principal reduction). Later EMIs are mostly principal repayment (less interest, since outstanding is lower). This is why foreclosing a loan in the first few years saves the most interest.' },
    ],
  },
  {
    slug: 'interest-rate',
    term: 'Interest Rate',
    shortDef: 'The percentage charged by a lender on the borrowed amount, expressed per annum.',
    metaTitle: 'What is Interest Rate on Loans? Types, India 2025 | Biddaro',
    metaDescription: 'Interest rate definition for loans in India — fixed vs floating, reducing balance vs flat rate, how it affects EMI. Current home loan rates 2025.',
    definition: 'Interest rate is the percentage of the outstanding loan amount that a lender charges as the cost of borrowing, typically expressed as an annual percentage (p.a.). In India, loan interest rates are either fixed (constant throughout tenure) or floating (changes with market rates linked to RBI repo rate or MCLR). The interest rate directly determines your EMI — a lower rate means lower monthly payments and less total interest paid over the loan tenure.',
    example: '₹25 Lakh home loan for 20 years: at 8.5% p.a. EMI = ₹21,696 and total interest = ₹27 Lakh. At 10% p.a. EMI = ₹24,126 and total interest = ₹33 Lakh. The 1.5% rate difference costs ₹6 Lakh extra over 20 years.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['emi', 'principal', 'tenure', 'processing-fee', 'foreclosure'],
    tags: ['interest rate loan india', 'home loan interest rate india', 'floating vs fixed rate loan'],
    faqs: [
      { q: 'What is the difference between fixed and floating interest rate?', a: 'A fixed interest rate stays the same throughout the loan tenure — your EMI never changes regardless of RBI rate decisions. A floating rate changes with market benchmarks (RLLR, MCLR, repo rate) — your EMI or tenure changes when rates move. In India, most home loans are floating rate. Fixed rates are typically 0.5–1% higher than floating rates initially but provide certainty. When RBI is raising rates (rate hike cycle), fixed is better; when rates are expected to fall, floating is better.' },
      { q: 'What is the reducing balance method for interest?', a: 'In the reducing balance method (used by all Indian banks/NBFCs), interest is calculated on the outstanding principal balance each month, not the original loan amount. As principal reduces each month, the interest component of the EMI decreases. This is different from the flat rate method (used by informal lenders), where interest is charged on the original principal throughout — making the effective rate much higher (a flat rate of 9% ≈ 16–18% reducing balance).' },
    ],
  },
  {
    slug: 'tenure',
    term: 'Tenure',
    shortDef: 'The duration of the loan — the agreed period within which the borrower must repay.',
    metaTitle: 'What is Loan Tenure? How It Affects EMI & Total Cost | Biddaro',
    metaDescription: 'Loan tenure meaning — how long you have to repay the loan. How tenure affects EMI and total interest. Right tenure for home loan, personal loan in India.',
    definition: 'Loan tenure (also called loan term) is the agreed time period within which a borrower must fully repay the loan — including principal and interest — through regular EMIs. Tenure is measured in months or years. Longer tenures result in lower monthly EMIs but higher total interest paid; shorter tenures have higher EMIs but lower total interest cost. The right tenure depends on your monthly cash flow and how much total interest you are willing to pay.',
    example: '₹15 Lakh loan at 9% p.a.: 5-year tenure = EMI ₹31,126, total interest ₹3.7L. 10-year tenure = EMI ₹18,999, total interest ₹7.8L. 20-year tenure = EMI ₹13,497, total interest ₹17.4L. Choosing 20 years saves ₹17,629/month but costs ₹13.7L more in total interest.',
    relatedLoanLink: '/loans/personal',
    relatedLoanName: 'Personal Loan',
    relatedTerms: ['emi', 'moratorium', 'foreclosure', 'interest-rate'],
    tags: ['loan tenure meaning', 'loan term india', 'home loan tenure'],
    faqs: [
      { q: 'What is the maximum loan tenure for home loans in India?', a: 'Maximum home loan tenure in India: salaried employees — up to 30 years (or until age 60–65 at maturity, whichever is earlier); self-employed — up to 20–25 years. Most construction loans have a maximum tenure of 20 years. Personal loans: maximum 5 years. Business loans: 5–7 years. Equipment finance: 5–7 years. Working capital: 12–36 months.' },
      { q: 'Should I choose a longer or shorter loan tenure?', a: 'Choose a shorter tenure if: you can afford higher EMIs, you want to minimize total interest paid, your income is stable and high relative to EMI. Choose a longer tenure if: you need lower EMIs for cash flow flexibility, you plan to make prepayments when income increases, or the interest rate differential is small. A practical approach: take a 20-year loan for lower EMI, then make annual prepayments of ₹1–2 Lakh to effectively reduce the tenure and save interest.' },
    ],
  },
  {
    slug: 'collateral',
    term: 'Collateral',
    shortDef: 'An asset pledged by the borrower as security against the loan.',
    metaTitle: 'What is Collateral in Loans? Types, Examples India | Biddaro',
    metaDescription: 'Collateral meaning in loans — assets pledged as security. Types of collateral accepted in India, secured vs unsecured loans, what happens if you default.',
    definition: 'Collateral is an asset owned by the borrower that is pledged to the lender as security for the loan. If the borrower fails to repay, the lender has the legal right to seize and sell the collateral to recover the outstanding amount. Loans with collateral are called secured loans (lower interest rates). Loans without collateral are unsecured (higher rates, lower amounts). Common collateral in India includes immovable property (land, buildings), fixed deposits, gold, and machinery.',
    example: 'Home construction loan: the plot of land and the building under construction are mortgaged as collateral. If you default, the lender can auction the property. Equipment finance: the JCB or excavator purchased is hypothecated. Personal loan: no collateral required — hence higher rate (14–24% vs 8.5–10% for secured loans).',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['ltv-ratio', 'noc', 'principal', 'co-applicant'],
    tags: ['collateral meaning loan india', 'secured loan collateral', 'what is collateral loan'],
    faqs: [
      { q: 'Can I get a loan without collateral in India?', a: 'Yes — personal loans, business loans (under CGTMSE scheme), and MUDRA loans are unsecured (no collateral). Working capital loans can be unsecured up to ₹10 Lakh. However, unsecured loans have higher interest rates (14–24% vs 8.5–12% for secured) and lower maximum amounts. For collateral-free business loans up to ₹2 Crore, CGTMSE provides a government guarantee to the lender.' },
      { q: 'What happens to collateral if I default on a loan?', a: 'If you default on a secured loan (EMI unpaid for 90+ days), the lender follows SARFAESI Act 2002 (for loans above ₹1 Lakh): they issue a notice, give 60 days to respond, then take possession of the collateral and sell it through an authorised auction. Proceeds first cover the outstanding loan, then lender\'s expenses; any surplus is returned to you. For residential property, lenders must give prior notice and opportunity to cure the default.' },
    ],
  },
  {
    slug: 'processing-fee',
    term: 'Processing Fee',
    shortDef: 'An upfront fee charged by lenders to cover loan application and administrative costs.',
    metaTitle: 'Processing Fee on Loans — What It Is and How Much? | Biddaro',
    metaDescription: 'Processing fee meaning in home loans, personal loans, business loans in India. Typical amounts, GST, negotiation tips, and what it covers.',
    definition: 'A processing fee is a one-time upfront charge levied by lenders to cover the cost of evaluating your loan application, running credit checks, legal and technical verifications, and administrative processing. It is typically a percentage of the loan amount (0.5–3%) plus 18% GST, deducted from the disbursed amount. The processing fee is non-refundable in most cases, even if the loan is not approved — verify this before paying.',
    example: '₹20 Lakh home loan with 1% processing fee = ₹20,000 + ₹3,600 GST = ₹23,600 total. You receive ₹19,76,400 (₹20L minus ₹23,600). For personal loan: 2% on ₹5 Lakh = ₹10,000 + ₹1,800 GST. Always factor processing fee into your total loan cost.',
    relatedLoanLink: '/loans/personal',
    relatedLoanName: 'Personal Loan',
    relatedTerms: ['interest-rate', 'tenure', 'foreclosure'],
    tags: ['processing fee loan india', 'loan origination fee', 'home loan processing fee india'],
    faqs: [
      { q: 'Is the processing fee refundable if the loan is rejected?', a: 'Processing fees are generally non-refundable — even if the loan is rejected after credit assessment. Some lenders refund the fee if they reject the application within the first 3–7 days (before full processing begins). Always ask about the refund policy before paying. If you withdraw the application yourself after paying, the fee is usually forfeited. This is why applying through Biddaro makes sense — we assess eligibility before you apply, reducing the risk of fee loss on a rejection.' },
      { q: 'Can the processing fee be negotiated?', a: 'Yes — processing fees are negotiable, especially for larger loan amounts, strong credit profiles (CIBIL 750+), or existing banking relationships. Common ways to get fee waivers: negotiate directly with the bank branch manager, apply during promotional periods (festive season — Diwali, Navratri — when banks offer zero processing fee campaigns), use a loan marketplace like Biddaro that negotiates fees in bulk with partner lenders.' },
    ],
  },
  {
    slug: 'foreclosure',
    term: 'Foreclosure',
    shortDef: 'Repaying the entire outstanding loan balance before the end of the tenure.',
    metaTitle: 'Loan Foreclosure Meaning India — Charges, Process, Savings | Biddaro',
    metaDescription: 'Foreclosure of loan meaning — paying off loan before tenure ends. RBI rules on foreclosure charges, how much you save, and the exact process.',
    definition: 'Loan foreclosure (also called preclosure or early closure) means paying off the entire remaining outstanding loan balance — principal and accrued interest — in a single payment before the loan tenure ends. This closes the loan account permanently. For floating rate home loans, RBI has prohibited foreclosure charges since 2014. Foreclosure saves all future interest that would have been paid over the remaining tenure.',
    example: '₹25 Lakh home loan, 20 years tenure, 8.5% rate. After 5 years, outstanding principal ≈ ₹22 Lakh, remaining interest for 15 years ≈ ₹19.5 Lakh. Foreclosing now by paying ₹22 Lakh saves ₹19.5 Lakh in future interest.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['emi', 'principal', 'tenure', 'processing-fee', 'balance-transfer'],
    tags: ['loan foreclosure india', 'preclosure loan india', 'foreclose home loan india'],
    faqs: [
      { q: 'Are there charges for foreclosing a home loan?', a: 'For floating rate home loans from banks and NBFCs, RBI has banned foreclosure charges since 2014 — you can pay off the loan anytime at zero penalty beyond the outstanding principal and accrued interest. For fixed rate home loans, lenders may charge 2–5% of outstanding. Personal loans may have 2–4% foreclosure charges with a 6–12 month lock-in period. Always confirm with your lender before planning foreclosure.' },
      { q: 'How do I foreclose my loan?', a: 'Step-by-step foreclosure: (1) Request a foreclosure statement from your lender (valid for 7–15 days showing exact payable amount); (2) Pay via RTGS/NEFT before the statement expires; (3) Collect the Loan Closure Certificate / No Dues Certificate within 7 days; (4) For secured loans, collect original property documents (lenders must return within 30 days per RBI); (5) Verify the loan shows as "Closed" on your CIBIL report within 45 days.' },
    ],
  },
  {
    slug: 'moratorium',
    term: 'Moratorium',
    shortDef: 'A temporary pause in loan EMI payments, during which interest continues to accrue.',
    metaTitle: 'Moratorium Period in Loans — Meaning, How It Works India | Biddaro',
    metaDescription: 'Moratorium period meaning in home loans, construction loans. Pre-EMI vs full EMI, how interest accrues, RBI COVID moratorium explained.',
    definition: 'A moratorium period (also called EMI holiday or repayment holiday) is a period at the beginning of a loan where the borrower is not required to pay full EMIs. It is commonly offered on construction loans during the construction phase — borrowers pay only the interest on disbursed amounts (called Pre-EMI) until construction is complete. Interest continues to accrue during moratorium and is either charged monthly or added to the outstanding principal.',
    example: 'Construction loan of ₹30 Lakh disbursed in stages. During 18-month construction, you pay Pre-EMI only on the disbursed amount: month 1 (₹5L disbursed) = ₹3,542 interest/month. After ₹30L fully disbursed: full EMI of ₹26,036/month begins.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['emi', 'principal', 'tenure', 'interest-rate'],
    tags: ['moratorium period loan india', 'pre-emi construction loan', 'emi holiday india'],
    faqs: [
      { q: 'Is moratorium period the same as grace period?', a: 'They are different: moratorium is a planned pause in full EMI payments (often at loan start, during construction); grace period is extra time given after an EMI due date before late charges apply (usually 3–7 days after due date). Construction loans offer a 12–36 month moratorium by design. During COVID-19 (2020), RBI allowed a special 6-month moratorium where interest accrued and was added to principal.' },
      { q: 'Should I take the moratorium or pay full EMI from day one?', a: 'Paying full EMI from day one (if you can afford it) is financially better — you reduce the principal faster and pay less total interest. The moratorium is a cash flow convenience, not a financial benefit. If your construction loan is ₹30 Lakh and you can pay ₹26,000 EMI from month 1, do so — you save lakhs in accrued interest compared to paying Pre-EMI for 18 months first.' },
    ],
  },
  {
    slug: 'co-applicant',
    term: 'Co-applicant',
    shortDef: 'A person who applies for a loan jointly with the primary borrower.',
    metaTitle: 'What is a Co-applicant in a Loan? Benefits, Rules India | Biddaro',
    metaDescription: 'Co-applicant meaning in home loan — who can be co-applicant, benefits of adding co-applicant, impact on eligibility, CIBIL score, and tax benefits.',
    definition: 'A co-applicant (also called joint applicant or co-borrower) is an additional person who applies for the loan jointly with the primary applicant. Both share equal liability for loan repayment. Adding a co-applicant with income increases the total eligible loan amount (since both incomes are considered), and typically improves approval chances. The loan appears on the CIBIL report of all co-applicants.',
    example: 'Husband alone: income ₹50,000/month → eligible for ₹25 Lakh loan. Wife\'s income: ₹35,000/month. Joint application: ₹85,000/month combined → eligible for ₹42–45 Lakh. Adding the wife as co-applicant increases eligibility by ₹17–20 Lakh.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['cibil-score', 'guarantor', 'principal', 'collateral'],
    tags: ['co-applicant home loan india', 'joint home loan india', 'co-borrower loan meaning'],
    faqs: [
      { q: 'Who can be a co-applicant for a home loan in India?', a: 'Accepted co-applicants: spouse (most common and recommended), parents, siblings (some lenders), children (earning adult children). Not accepted as co-applicants: friends, business partners (for personal home loans), distant relatives (most lenders). For construction loans, the co-applicant must ideally have a co-ownership stake in the property or the plot being mortgaged.' },
      { q: 'Does adding a co-applicant affect tax benefits?', a: 'Yes — tax benefits are proportional to each applicant\'s share of EMI repayment. Both co-applicants can individually claim Section 24(b) deduction (interest up to ₹2 Lakh p.a.) and Section 80C deduction (principal up to ₹1.5 Lakh) — effectively doubling the household tax benefit. Co-ownership of the property is recommended (not just co-borrowing) to maximise individual deduction claims.' },
    ],
  },
  {
    slug: 'guarantor',
    term: 'Guarantor',
    shortDef: 'A person who promises to repay the loan if the primary borrower defaults.',
    metaTitle: 'What is a Guarantor in a Loan? Risks, Rights India 2025 | Biddaro',
    metaDescription: 'Guarantor meaning in loans India — responsibilities, risks, CIBIL impact, difference from co-applicant. What happens when the borrower defaults.',
    definition: 'A guarantor is a third person who provides a guarantee to the lender that they will repay the loan if the primary borrower fails to do so. Unlike a co-applicant (who shares primary liability), a guarantor\'s liability is secondary — the lender first pursues the borrower, then the guarantor. However, in practice, if the borrower defaults, the guarantor\'s CIBIL score is damaged and they can be legally pursued for full repayment.',
    example: 'Ravi applies for ₹10 Lakh business loan but has low CIBIL (680). His friend Suresh (CIBIL 780, stable income) agrees to be guarantor. The lender approves based on Suresh\'s creditworthiness. If Ravi defaults 6 months later, Suresh\'s CIBIL drops and the lender can sue Suresh for ₹9.5 Lakh outstanding.',
    relatedLoanLink: '/loans/business',
    relatedLoanName: 'Business Loan',
    relatedTerms: ['co-applicant', 'cibil-score', 'collateral', 'principal'],
    tags: ['guarantor loan india', 'loan guarantor meaning', 'guarantor liability india'],
    faqs: [
      { q: 'What are the risks of being a loan guarantor?', a: 'Becoming a guarantor carries significant risks: (1) CIBIL impact — the loan appears on your CIBIL report; any default by the borrower damages your credit score; (2) Legal liability — if the borrower defaults, the lender can sue you for the full outstanding amount; (3) Loan eligibility impact — the guaranteed loan is counted in your own FOIR when you apply for loans; (4) Asset risk — if you have pledged personal assets as guarantee, they can be seized. Never be a guarantor unless you trust the borrower completely and can afford to repay the loan yourself.' },
      { q: 'Can a guarantor be removed from a loan?', a: 'Removing a guarantor mid-loan is possible but difficult — the lender must agree, and typically requires a substitute guarantor of equal creditworthiness. Alternative: the borrower\'s income/CIBIL improvement may allow the lender to release the guarantor. Best time: when the loan is 50–60% repaid and the borrower has demonstrated strong repayment history. The process requires a formal request to the bank, credit re-evaluation, and potentially new loan documentation.' },
    ],
  },
  {
    slug: 'ltv-ratio',
    term: 'LTV Ratio',
    shortDef: 'Loan-to-Value ratio — the percentage of the property value that a lender will finance.',
    metaTitle: 'What is LTV Ratio in Home Loans? India 2025 — RBI Guidelines | Biddaro',
    metaDescription: 'LTV ratio meaning in home loans India — how it determines maximum loan amount, RBI guidelines, down payment calculation. Examples for ₹30L, ₹50L, ₹1Cr loans.',
    definition: 'Loan-to-Value (LTV) ratio is the maximum percentage of the property\'s assessed market value that a lender is willing to finance as a loan. The remaining percentage is the borrower\'s down payment (margin). RBI sets maximum LTV limits for home loans: up to 75% for loans above ₹75 Lakh, up to 80% for ₹30–75 Lakh, and up to 90% for loans below ₹30 Lakh. Higher LTV = less down payment required but higher EMI.',
    example: 'Property value: ₹80 Lakh. At 75% LTV (RBI max for >₹75L loans): maximum loan = ₹60 Lakh, down payment = ₹20 Lakh. If the same property is assessed at ₹50 Lakh: at 80% LTV, maximum loan = ₹40 Lakh, down payment = ₹10 Lakh.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['collateral', 'principal', 'interest-rate', 'noc'],
    tags: ['LTV ratio home loan india', 'loan to value ratio', 'down payment home loan india', 'RBI LTV guidelines'],
    faqs: [
      { q: 'What is the maximum LTV for home loans per RBI guidelines 2025?', a: 'RBI maximum LTV ratios for home loans: up to ₹30 Lakh — 90% LTV (10% down payment); ₹30–75 Lakh — 80% LTV (20% down payment); above ₹75 Lakh — 75% LTV (25% down payment). These are maximums — individual lenders may offer lower LTV based on borrower profile, property location, and type (under-construction properties often get lower LTV than ready properties).' },
      { q: 'How is LTV calculated for construction loans?', a: 'For construction loans, LTV is calculated on the total project cost: plot value + construction cost (as per approved estimate). Example: plot value ₹20 Lakh + construction estimate ₹40 Lakh = total project ₹60 Lakh. At 80% LTV: maximum loan = ₹48 Lakh. The remaining ₹12 Lakh is your down payment. Lenders disburse the loan in stages as construction progresses, not as a lump sum.' },
    ],
  },
  {
    slug: 'dpd',
    term: 'DPD',
    shortDef: 'Days Past Due — the number of days a loan payment is overdue.',
    metaTitle: 'What is DPD in Loan? Days Past Due Meaning India | Biddaro',
    metaDescription: 'DPD meaning in CIBIL report — days past due, how it affects your credit score, what different DPD buckets mean, and how to clear DPD from CIBIL.',
    definition: 'DPD (Days Past Due) is the number of days a borrower has been overdue on a loan EMI payment. It appears in your CIBIL report for each loan account, updated monthly by the lender. DPD of 0 means payments were on time. Any positive DPD — 30, 60, 90 days — indicates late or missed payments. DPD significantly impacts your CIBIL score; even a single 30+ DPD can drop your score by 50–80 points.',
    example: 'Your home loan EMI was due on the 5th but you paid on the 20th — 15 days late. CIBIL shows "015 DPD" for that month. If unpaid for 60 days, it shows "060 DPD." After 90 days, the account may be marked as NPA (Non-Performing Asset), severely damaging your credit profile.',
    relatedLoanLink: '/loans/personal',
    relatedLoanName: 'Personal Loan',
    relatedTerms: ['cibil-score', 'nach-mandate', 'emi'],
    tags: ['DPD meaning CIBIL', 'days past due loan india', 'overdue payment CIBIL'],
    faqs: [
      { q: 'How long does DPD stay on my CIBIL report?', a: 'DPD entries stay on your CIBIL report for 7 years from the date of the incident. Even after you pay the overdue amount, the historical DPD remains visible to lenders for 7 years. However, after 24–36 months of clean repayment history, most lenders start discounting old DPD entries (particularly if they were isolated incidents). DPD from more than 3 years ago with perfect repayment since then is often forgiven by lenders.' },
      { q: 'Can I remove DPD from my CIBIL report?', a: 'You cannot remove accurate DPD entries from your CIBIL report — if you genuinely missed a payment, it will remain for 7 years. However, if the DPD entry is an error (you paid on time but the lender reported wrongly), dispute it at cibil.com with payment proof. The lender has 30 days to correct the record. Some lenders also offer a "DPD waiver" letter stating that the delay was due to banking issues on their end, which you can attach to your next loan application as an explanation.' },
    ],
  },
  {
    slug: 'nach-mandate',
    term: 'NACH Mandate',
    shortDef: 'National Automated Clearing House — a system that auto-debits your EMI from your bank account.',
    metaTitle: 'What is NACH Mandate for Loan EMI? How It Works India | Biddaro',
    metaDescription: 'NACH mandate meaning for loan repayment — how auto-debit works, how to set up, what happens if mandate bounces, how to cancel.',
    definition: 'NACH (National Automated Clearing House) is an electronic clearing system operated by NPCI (National Payments Corporation of India) that allows lenders to automatically debit your EMI from your bank account on the due date every month. When you take a loan, you sign a NACH mandate authorising this auto-debit. This ensures timely repayment without manual transfers. Bouncing a NACH mandate (insufficient balance) attracts a bounce charge and is reported as a late payment to CIBIL.',
    example: 'Your home loan EMI of ₹18,500 is due on the 5th. NACH mandate auto-debits ₹18,500 from your savings account every 5th. If your account has only ₹15,000 on that date, the NACH bounces — the lender charges ₹500–₹1,500 bounce fee and your CIBIL reflects a missed EMI.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['emi', 'dpd', 'cibil-score'],
    tags: ['NACH mandate loan india', 'auto debit EMI india', 'NACH bounce charges india'],
    faqs: [
      { q: 'What happens if NACH mandate bounces?', a: 'If your NACH mandate bounces (account has insufficient funds): (1) Lender charges bounce fee of ₹500–₹1,500 + GST; (2) EMI is considered unpaid for that day — starts accruing DPD (Days Past Due); (3) After 30 days, the lender reports 30 DPD to CIBIL; (4) Lender typically makes 2–3 NACH presentation attempts in the same month. Best practice: keep a buffer of 2 months\' EMI in your linked savings account. Set a reminder 2 days before due date to ensure sufficient balance.' },
      { q: 'Can I change the bank account linked to NACH mandate?', a: 'Yes — you can change the bank account for NACH after the loan is sanctioned. Process: submit a mandate cancellation request for the old account + new mandate form for the new account to the lender. This takes 7–15 working days. During this transition, pay EMI manually via NEFT/RTGS to avoid missing a payment. Some lenders process this digitally through net banking. Ensure the new account has sufficient balance from the first auto-debit date.' },
    ],
  },
  {
    slug: 'noc',
    term: 'NOC',
    shortDef: 'No Objection Certificate — a document confirming no outstanding disputes on a property or loan.',
    metaTitle: 'NOC Meaning in Loans & Property India — When Is It Required? | Biddaro',
    metaDescription: 'NOC meaning in home loans and property transactions — types of NOC, when required, how to get society NOC, builder NOC, lender NOC in India.',
    definition: 'NOC (No Objection Certificate) is a legal document issued by a person or authority stating that they have no objection to a specified action. In home loans, NOCs are required from multiple parties: the housing society (for mortgaging a flat), the builder (for under-construction properties), the municipal authority (building completion), and previous lenders (after full loan repayment). Without the relevant NOC, loan disbursement cannot proceed.',
    example: 'You want to mortgage your apartment in a cooperative housing society for a top-up loan. The society issues a NOC stating: "We have no objection to Mr. Ravi Kumar mortgaging Flat 4B to HDFC Bank." This NOC, along with your property documents, enables the lender to proceed.',
    relatedLoanLink: '/loans/home-construction',
    relatedLoanName: 'Home Construction Loan',
    relatedTerms: ['collateral', 'ltv-ratio', 'co-applicant'],
    tags: ['NOC meaning loan india', 'society NOC home loan', 'no objection certificate property india'],
    faqs: [
      { q: 'What is an NOC from the previous lender?', a: 'When you fully repay a home loan, your lender must issue an NOC confirming zero outstanding dues and release all original property documents. RBI mandates lenders to return documents within 30 days of loan closure. This NOC is critical — without it, you cannot sell, gift, or create a fresh mortgage on the property. If the lender delays, you can file a complaint with the Banking Ombudsman. Keep this NOC safely as you\'ll need it for future property transactions.' },
      { q: 'What is a society NOC and when is it required?', a: 'A society NOC is a letter from the cooperative housing society stating no objection to mortgaging your flat with a lender. Required when: taking a home loan on a flat within a registered housing cooperative, doing a balance transfer, or selling the flat (buyer\'s lender requires it). Obtained by writing to the managing committee with your loan details and paying a small fee (₹500–₹2,000). Refusal is possible only if maintenance dues are pending — clear them first.' },
    ],
  },
];

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_TERMS.find(t => t.slug === slug);
}
